# See https://docs.aspect.build/workflows/configuration
tasks:
  - branch_freshness:
      update_strategy: none
  - format:
      queue: aspect-medium
  - buildifier:
      queue: aspect-medium
  - configure:
      queue: aspect-medium
  - test:
  - finalization:
      queue: aspect-small
notifications:
  github: {}
