// @generated by protoc-gen-es v1.8.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file cli/core/bazel/action_cache/action_cache.proto (package bazel, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message bazel.ActionCacheStatistics
 */
export declare class ActionCacheStatistics extends Message<ActionCacheStatistics> {
  /**
   * @generated from field: uint64 size_in_bytes = 1;
   */
  sizeInBytes: bigint;

  /**
   * @generated from field: uint64 save_time_in_ms = 2;
   */
  saveTimeInMs: bigint;

  /**
   * @generated from field: int32 hits = 3;
   */
  hits: number;

  /**
   * @generated from field: int32 misses = 4;
   */
  misses: number;

  /**
   * @generated from field: repeated bazel.ActionCacheStatistics.MissDetail miss_details = 5;
   */
  missDetails: ActionCacheStatistics_MissDetail[];

  /**
   * @generated from field: uint64 load_time_in_ms = 6;
   */
  loadTimeInMs: bigint;

  constructor(data?: PartialMessage<ActionCacheStatistics>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bazel.ActionCacheStatistics";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActionCacheStatistics;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActionCacheStatistics;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActionCacheStatistics;

  static equals(a: ActionCacheStatistics | PlainMessage<ActionCacheStatistics> | undefined, b: ActionCacheStatistics | PlainMessage<ActionCacheStatistics> | undefined): boolean;
}

/**
 * @generated from enum bazel.ActionCacheStatistics.MissReason
 */
export declare enum ActionCacheStatistics_MissReason {
  /**
   * @generated from enum value: DIFFERENT_ACTION_KEY = 0;
   */
  DIFFERENT_ACTION_KEY = 0,

  /**
   * @generated from enum value: DIFFERENT_DEPS = 1;
   */
  DIFFERENT_DEPS = 1,

  /**
   * @generated from enum value: DIFFERENT_ENVIRONMENT = 2;
   */
  DIFFERENT_ENVIRONMENT = 2,

  /**
   * @generated from enum value: DIFFERENT_FILES = 3;
   */
  DIFFERENT_FILES = 3,

  /**
   * @generated from enum value: CORRUPTED_CACHE_ENTRY = 4;
   */
  CORRUPTED_CACHE_ENTRY = 4,

  /**
   * @generated from enum value: NOT_CACHED = 5;
   */
  NOT_CACHED = 5,

  /**
   * @generated from enum value: UNCONDITIONAL_EXECUTION = 6;
   */
  UNCONDITIONAL_EXECUTION = 6,
}

/**
 * @generated from message bazel.ActionCacheStatistics.MissDetail
 */
export declare class ActionCacheStatistics_MissDetail extends Message<ActionCacheStatistics_MissDetail> {
  /**
   * @generated from field: bazel.ActionCacheStatistics.MissReason reason = 1;
   */
  reason: ActionCacheStatistics_MissReason;

  /**
   * @generated from field: int32 count = 2;
   */
  count: number;

  constructor(data?: PartialMessage<ActionCacheStatistics_MissDetail>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bazel.ActionCacheStatistics.MissDetail";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActionCacheStatistics_MissDetail;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActionCacheStatistics_MissDetail;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActionCacheStatistics_MissDetail;

  static equals(a: ActionCacheStatistics_MissDetail | PlainMessage<ActionCacheStatistics_MissDetail> | undefined, b: ActionCacheStatistics_MissDetail | PlainMessage<ActionCacheStatistics_MissDetail> | undefined): boolean;
}

