workflow:
  rules:
    # Run for everything except tag pushes
    - if: "$CI_COMMIT_TAG == null"

stages:
  - Aspect Workflows

pre-build:
  stage: Aspect Workflows
  script:
    - echo "Build and upload CLI to remote cache"
    - .aspect/bootstrap.sh
  tags:
    - aspect-workflows
    - aspect-default

build-task:
  stage: Aspect Workflows
  needs: [pre-build]
  tags:
    - aspect-workflows
    - aspect-default
  script:
    - .aspect/bootstrap.sh
    - ASPECT_DEBUG=1 aspect build //...
    - aspect build --task-key build-gl //...

test-task:
  stage: Aspect Workflows
  needs: [pre-build]
  tags:
    - aspect-workflows
    - aspect-default
  script:
    - .aspect/bootstrap.sh
    - ASPECT_DEBUG=1 aspect test //...
    - aspect test --task-key test-gl //...

delivery-task:
  stage: Aspect Workflows
  needs: [pre-build]
  tags:
    - aspect-workflows
    - aspect-default
  script:
    - .aspect/bootstrap.sh
    - ASPECT_DEBUG=1 aspect delivery --build_url $CI_PIPELINE_URL --commit_sha $CI_COMMIT_SHA --force_target //:hello -- //:hello //:hello2
    - aspect delivery --task-key delivery-gl --build_url $CI_PIPELINE_URL --commit_sha $CI_COMMIT_SHA --force_target //:hello -- //:hello //:hello2
