// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: pkg/plugin/sdk/v1alpha4/proto/plugin.proto

package proto

import (
	context "context"
	buildeventstream "github.com/aspect-build/aspect-cli/bazel/buildeventstream"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BEPEventCallbackReq struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Event          *buildeventstream.BuildEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	SequenceNumber int64                        `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BEPEventCallbackReq) Reset() {
	*x = BEPEventCallbackReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BEPEventCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEPEventCallbackReq) ProtoMessage() {}

func (x *BEPEventCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEPEventCallbackReq.ProtoReflect.Descriptor instead.
func (*BEPEventCallbackReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *BEPEventCallbackReq) GetEvent() *buildeventstream.BuildEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BEPEventCallbackReq) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type BEPEventCallbackRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BEPEventCallbackRes) Reset() {
	*x = BEPEventCallbackRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BEPEventCallbackRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEPEventCallbackRes) ProtoMessage() {}

func (x *BEPEventCallbackRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEPEventCallbackRes.ProtoReflect.Descriptor instead.
func (*BEPEventCallbackRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{1}
}

type SetupReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Properties []byte                 `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	// Deprecated: Marked as deprecated in pkg/plugin/sdk/v1alpha4/proto/plugin.proto.
	File          *File `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupReq) Reset() {
	*x = SetupReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupReq) ProtoMessage() {}

func (x *SetupReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupReq.ProtoReflect.Descriptor instead.
func (*SetupReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *SetupReq) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Deprecated: Marked as deprecated in pkg/plugin/sdk/v1alpha4/proto/plugin.proto.
func (x *SetupReq) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRes) Reset() {
	*x = SetupRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRes) ProtoMessage() {}

func (x *SetupRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRes.ProtoReflect.Descriptor instead.
func (*SetupRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{4}
}

type PostBuildHookReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BrokerId          uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	IsInteractiveMode bool                   `protobuf:"varint,2,opt,name=is_interactive_mode,json=isInteractiveMode,proto3" json:"is_interactive_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostBuildHookReq) Reset() {
	*x = PostBuildHookReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBuildHookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBuildHookReq) ProtoMessage() {}

func (x *PostBuildHookReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBuildHookReq.ProtoReflect.Descriptor instead.
func (*PostBuildHookReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PostBuildHookReq) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *PostBuildHookReq) GetIsInteractiveMode() bool {
	if x != nil {
		return x.IsInteractiveMode
	}
	return false
}

type PostBuildHookRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBuildHookRes) Reset() {
	*x = PostBuildHookRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBuildHookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBuildHookRes) ProtoMessage() {}

func (x *PostBuildHookRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBuildHookRes.ProtoReflect.Descriptor instead.
func (*PostBuildHookRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{6}
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Use           string                 `protobuf:"bytes,1,opt,name=use,proto3" json:"use,omitempty"`
	ShortDesc     string                 `protobuf:"bytes,2,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	LongDesc      string                 `protobuf:"bytes,3,opt,name=long_desc,json=longDesc,proto3" json:"long_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Command) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *Command) GetLongDesc() string {
	if x != nil {
		return x.LongDesc
	}
	return ""
}

type CustomCommandsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCommandsReq) Reset() {
	*x = CustomCommandsReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCommandsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCommandsReq) ProtoMessage() {}

func (x *CustomCommandsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCommandsReq.ProtoReflect.Descriptor instead.
func (*CustomCommandsReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{8}
}

type CustomCommandsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCommandsRes) Reset() {
	*x = CustomCommandsRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCommandsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCommandsRes) ProtoMessage() {}

func (x *CustomCommandsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCommandsRes.ProtoReflect.Descriptor instead.
func (*CustomCommandsRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *CustomCommandsRes) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceRoot string                 `protobuf:"bytes,1,opt,name=workspaceRoot,proto3" json:"workspaceRoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Context) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

type ExecuteCustomCommandReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomCommand    string                 `protobuf:"bytes,1,opt,name=customCommand,proto3" json:"customCommand,omitempty"`
	Ctx              *Context               `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Args             []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	BazelStartupArgs []string               `protobuf:"bytes,4,rep,name=bazelStartupArgs,proto3" json:"bazelStartupArgs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteCustomCommandReq) Reset() {
	*x = ExecuteCustomCommandReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCustomCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCustomCommandReq) ProtoMessage() {}

func (x *ExecuteCustomCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCustomCommandReq.ProtoReflect.Descriptor instead.
func (*ExecuteCustomCommandReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteCustomCommandReq) GetCustomCommand() string {
	if x != nil {
		return x.CustomCommand
	}
	return ""
}

func (x *ExecuteCustomCommandReq) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ExecuteCustomCommandReq) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCustomCommandReq) GetBazelStartupArgs() []string {
	if x != nil {
		return x.BazelStartupArgs
	}
	return nil
}

type ExecuteCustomCommandRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCustomCommandRes) Reset() {
	*x = ExecuteCustomCommandRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCustomCommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCustomCommandRes) ProtoMessage() {}

func (x *ExecuteCustomCommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCustomCommandRes.ProtoReflect.Descriptor instead.
func (*ExecuteCustomCommandRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{12}
}

type PostTestHookReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BrokerId          uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	IsInteractiveMode bool                   `protobuf:"varint,2,opt,name=is_interactive_mode,json=isInteractiveMode,proto3" json:"is_interactive_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostTestHookReq) Reset() {
	*x = PostTestHookReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTestHookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTestHookReq) ProtoMessage() {}

func (x *PostTestHookReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTestHookReq.ProtoReflect.Descriptor instead.
func (*PostTestHookReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PostTestHookReq) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *PostTestHookReq) GetIsInteractiveMode() bool {
	if x != nil {
		return x.IsInteractiveMode
	}
	return false
}

type PostTestHookRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTestHookRes) Reset() {
	*x = PostTestHookRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTestHookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTestHookRes) ProtoMessage() {}

func (x *PostTestHookRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTestHookRes.ProtoReflect.Descriptor instead.
func (*PostTestHookRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{14}
}

type PostRunHookReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BrokerId          uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	IsInteractiveMode bool                   `protobuf:"varint,2,opt,name=is_interactive_mode,json=isInteractiveMode,proto3" json:"is_interactive_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostRunHookReq) Reset() {
	*x = PostRunHookReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRunHookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRunHookReq) ProtoMessage() {}

func (x *PostRunHookReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRunHookReq.ProtoReflect.Descriptor instead.
func (*PostRunHookReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *PostRunHookReq) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *PostRunHookReq) GetIsInteractiveMode() bool {
	if x != nil {
		return x.IsInteractiveMode
	}
	return false
}

type PostRunHookRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRunHookRes) Reset() {
	*x = PostRunHookRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRunHookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRunHookRes) ProtoMessage() {}

func (x *PostRunHookRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRunHookRes.ProtoReflect.Descriptor instead.
func (*PostRunHookRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{16}
}

type PromptRunReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Default       string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	AllowEdit     bool                   `protobuf:"varint,3,opt,name=allow_edit,json=allowEdit,proto3" json:"allow_edit,omitempty"`
	Mask          string                 `protobuf:"bytes,5,opt,name=mask,proto3" json:"mask,omitempty"`
	HideEntered   bool                   `protobuf:"varint,6,opt,name=hide_entered,json=hideEntered,proto3" json:"hide_entered,omitempty"`
	IsConfirm     bool                   `protobuf:"varint,8,opt,name=is_confirm,json=isConfirm,proto3" json:"is_confirm,omitempty"`
	IsVimMode     bool                   `protobuf:"varint,9,opt,name=is_vim_mode,json=isVimMode,proto3" json:"is_vim_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRunReq) Reset() {
	*x = PromptRunReq{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRunReq) ProtoMessage() {}

func (x *PromptRunReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRunReq.ProtoReflect.Descriptor instead.
func (*PromptRunReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PromptRunReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PromptRunReq) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *PromptRunReq) GetAllowEdit() bool {
	if x != nil {
		return x.AllowEdit
	}
	return false
}

func (x *PromptRunReq) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *PromptRunReq) GetHideEntered() bool {
	if x != nil {
		return x.HideEntered
	}
	return false
}

func (x *PromptRunReq) GetIsConfirm() bool {
	if x != nil {
		return x.IsConfirm
	}
	return false
}

func (x *PromptRunReq) GetIsVimMode() bool {
	if x != nil {
		return x.IsVimMode
	}
	return false
}

type PromptRunRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         *PromptRunRes_Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRunRes) Reset() {
	*x = PromptRunRes{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRunRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRunRes) ProtoMessage() {}

func (x *PromptRunRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRunRes.ProtoReflect.Descriptor instead.
func (*PromptRunRes) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *PromptRunRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PromptRunRes) GetError() *PromptRunRes_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PromptRunRes_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Happened      bool                   `protobuf:"varint,1,opt,name=happened,proto3" json:"happened,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRunRes_Error) Reset() {
	*x = PromptRunRes_Error{}
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRunRes_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRunRes_Error) ProtoMessage() {}

func (x *PromptRunRes_Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRunRes_Error.ProtoReflect.Descriptor instead.
func (*PromptRunRes_Error) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP(), []int{18, 0}
}

func (x *PromptRunRes_Error) GetHappened() bool {
	if x != nil {
		return x.Happened
	}
	return false
}

func (x *PromptRunRes_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_plugin_sdk_v1alpha4_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"*pkg/plugin/sdk/v1alpha4/proto/plugin.proto\x12\x05proto\x1a/bazel/buildeventstream/build_event_stream.proto\"t\n" +
	"\x13BEPEventCallbackReq\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1e.build_event_stream.BuildEventR\x05event\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\"\x15\n" +
	"\x13BEPEventCallbackRes\"O\n" +
	"\bSetupReq\x12\x1e\n" +
	"\n" +
	"properties\x18\x01 \x01(\fR\n" +
	"properties\x12#\n" +
	"\x04file\x18\x02 \x01(\v2\v.proto.FileB\x02\x18\x01R\x04file\"\x1a\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\n" +
	"\n" +
	"\bSetupRes\"_\n" +
	"\x10PostBuildHookReq\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12.\n" +
	"\x13is_interactive_mode\x18\x02 \x01(\bR\x11isInteractiveMode\"\x12\n" +
	"\x10PostBuildHookRes\"W\n" +
	"\aCommand\x12\x10\n" +
	"\x03use\x18\x01 \x01(\tR\x03use\x12\x1d\n" +
	"\n" +
	"short_desc\x18\x02 \x01(\tR\tshortDesc\x12\x1b\n" +
	"\tlong_desc\x18\x03 \x01(\tR\blongDesc\"\x13\n" +
	"\x11CustomCommandsReq\"?\n" +
	"\x11CustomCommandsRes\x12*\n" +
	"\bcommands\x18\x01 \x03(\v2\x0e.proto.CommandR\bcommands\"/\n" +
	"\aContext\x12$\n" +
	"\rworkspaceRoot\x18\x01 \x01(\tR\rworkspaceRoot\"\xa1\x01\n" +
	"\x17ExecuteCustomCommandReq\x12$\n" +
	"\rcustomCommand\x18\x01 \x01(\tR\rcustomCommand\x12 \n" +
	"\x03ctx\x18\x02 \x01(\v2\x0e.proto.ContextR\x03ctx\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12*\n" +
	"\x10bazelStartupArgs\x18\x04 \x03(\tR\x10bazelStartupArgs\"\x19\n" +
	"\x17ExecuteCustomCommandRes\"^\n" +
	"\x0fPostTestHookReq\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12.\n" +
	"\x13is_interactive_mode\x18\x02 \x01(\bR\x11isInteractiveMode\"\x11\n" +
	"\x0fPostTestHookRes\"]\n" +
	"\x0ePostRunHookReq\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12.\n" +
	"\x13is_interactive_mode\x18\x02 \x01(\bR\x11isInteractiveMode\"\x10\n" +
	"\x0ePostRunHookRes\"\xd3\x01\n" +
	"\fPromptRunReq\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x12\x1d\n" +
	"\n" +
	"allow_edit\x18\x03 \x01(\bR\tallowEdit\x12\x12\n" +
	"\x04mask\x18\x05 \x01(\tR\x04mask\x12!\n" +
	"\fhide_entered\x18\x06 \x01(\bR\vhideEntered\x12\x1d\n" +
	"\n" +
	"is_confirm\x18\b \x01(\bR\tisConfirm\x12\x1e\n" +
	"\vis_vim_mode\x18\t \x01(\bR\tisVimMode\"\x96\x01\n" +
	"\fPromptRunRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x19.proto.PromptRunRes.ErrorR\x05error\x1a=\n" +
	"\x05Error\x12\x1a\n" +
	"\bhappened\x18\x01 \x01(\bR\bhappened\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xdd\x03\n" +
	"\x06Plugin\x12J\n" +
	"\x10BEPEventCallback\x12\x1a.proto.BEPEventCallbackReq\x1a\x1a.proto.BEPEventCallbackRes\x12D\n" +
	"\x0eCustomCommands\x12\x18.proto.CustomCommandsReq\x1a\x18.proto.CustomCommandsRes\x12V\n" +
	"\x14ExecuteCustomCommand\x12\x1e.proto.ExecuteCustomCommandReq\x1a\x1e.proto.ExecuteCustomCommandRes\x12A\n" +
	"\rPostBuildHook\x12\x17.proto.PostBuildHookReq\x1a\x17.proto.PostBuildHookRes\x12>\n" +
	"\fPostTestHook\x12\x16.proto.PostTestHookReq\x1a\x16.proto.PostTestHookRes\x12;\n" +
	"\vPostRunHook\x12\x15.proto.PostRunHookReq\x1a\x15.proto.PostRunHookRes\x12)\n" +
	"\x05Setup\x12\x0f.proto.SetupReq\x1a\x0f.proto.SetupRes2;\n" +
	"\bPrompter\x12/\n" +
	"\x03Run\x12\x13.proto.PromptRunReq\x1a\x13.proto.PromptRunResBBZ@github.com/aspect-build/aspect-cli/pkg/plugin/sdk/v1alpha4/protob\x06proto3"

var (
	file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDesc), len(file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_goTypes = []any{
	(*BEPEventCallbackReq)(nil),         // 0: proto.BEPEventCallbackReq
	(*BEPEventCallbackRes)(nil),         // 1: proto.BEPEventCallbackRes
	(*SetupReq)(nil),                    // 2: proto.SetupReq
	(*File)(nil),                        // 3: proto.File
	(*SetupRes)(nil),                    // 4: proto.SetupRes
	(*PostBuildHookReq)(nil),            // 5: proto.PostBuildHookReq
	(*PostBuildHookRes)(nil),            // 6: proto.PostBuildHookRes
	(*Command)(nil),                     // 7: proto.Command
	(*CustomCommandsReq)(nil),           // 8: proto.CustomCommandsReq
	(*CustomCommandsRes)(nil),           // 9: proto.CustomCommandsRes
	(*Context)(nil),                     // 10: proto.Context
	(*ExecuteCustomCommandReq)(nil),     // 11: proto.ExecuteCustomCommandReq
	(*ExecuteCustomCommandRes)(nil),     // 12: proto.ExecuteCustomCommandRes
	(*PostTestHookReq)(nil),             // 13: proto.PostTestHookReq
	(*PostTestHookRes)(nil),             // 14: proto.PostTestHookRes
	(*PostRunHookReq)(nil),              // 15: proto.PostRunHookReq
	(*PostRunHookRes)(nil),              // 16: proto.PostRunHookRes
	(*PromptRunReq)(nil),                // 17: proto.PromptRunReq
	(*PromptRunRes)(nil),                // 18: proto.PromptRunRes
	(*PromptRunRes_Error)(nil),          // 19: proto.PromptRunRes.Error
	(*buildeventstream.BuildEvent)(nil), // 20: build_event_stream.BuildEvent
}
var file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_depIdxs = []int32{
	20, // 0: proto.BEPEventCallbackReq.event:type_name -> build_event_stream.BuildEvent
	3,  // 1: proto.SetupReq.file:type_name -> proto.File
	7,  // 2: proto.CustomCommandsRes.commands:type_name -> proto.Command
	10, // 3: proto.ExecuteCustomCommandReq.ctx:type_name -> proto.Context
	19, // 4: proto.PromptRunRes.error:type_name -> proto.PromptRunRes.Error
	0,  // 5: proto.Plugin.BEPEventCallback:input_type -> proto.BEPEventCallbackReq
	8,  // 6: proto.Plugin.CustomCommands:input_type -> proto.CustomCommandsReq
	11, // 7: proto.Plugin.ExecuteCustomCommand:input_type -> proto.ExecuteCustomCommandReq
	5,  // 8: proto.Plugin.PostBuildHook:input_type -> proto.PostBuildHookReq
	13, // 9: proto.Plugin.PostTestHook:input_type -> proto.PostTestHookReq
	15, // 10: proto.Plugin.PostRunHook:input_type -> proto.PostRunHookReq
	2,  // 11: proto.Plugin.Setup:input_type -> proto.SetupReq
	17, // 12: proto.Prompter.Run:input_type -> proto.PromptRunReq
	1,  // 13: proto.Plugin.BEPEventCallback:output_type -> proto.BEPEventCallbackRes
	9,  // 14: proto.Plugin.CustomCommands:output_type -> proto.CustomCommandsRes
	12, // 15: proto.Plugin.ExecuteCustomCommand:output_type -> proto.ExecuteCustomCommandRes
	6,  // 16: proto.Plugin.PostBuildHook:output_type -> proto.PostBuildHookRes
	14, // 17: proto.Plugin.PostTestHook:output_type -> proto.PostTestHookRes
	16, // 18: proto.Plugin.PostRunHook:output_type -> proto.PostRunHookRes
	4,  // 19: proto.Plugin.Setup:output_type -> proto.SetupRes
	18, // 20: proto.Prompter.Run:output_type -> proto.PromptRunRes
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_init() }
func file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_init() {
	if File_pkg_plugin_sdk_v1alpha4_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDesc), len(file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_sdk_v1alpha4_proto_plugin_proto = out.File
	file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_sdk_v1alpha4_proto_plugin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	BEPEventCallback(ctx context.Context, in *BEPEventCallbackReq, opts ...grpc.CallOption) (*BEPEventCallbackRes, error)
	CustomCommands(ctx context.Context, in *CustomCommandsReq, opts ...grpc.CallOption) (*CustomCommandsRes, error)
	ExecuteCustomCommand(ctx context.Context, in *ExecuteCustomCommandReq, opts ...grpc.CallOption) (*ExecuteCustomCommandRes, error)
	PostBuildHook(ctx context.Context, in *PostBuildHookReq, opts ...grpc.CallOption) (*PostBuildHookRes, error)
	PostTestHook(ctx context.Context, in *PostTestHookReq, opts ...grpc.CallOption) (*PostTestHookRes, error)
	PostRunHook(ctx context.Context, in *PostRunHookReq, opts ...grpc.CallOption) (*PostRunHookRes, error)
	Setup(ctx context.Context, in *SetupReq, opts ...grpc.CallOption) (*SetupRes, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) BEPEventCallback(ctx context.Context, in *BEPEventCallbackReq, opts ...grpc.CallOption) (*BEPEventCallbackRes, error) {
	out := new(BEPEventCallbackRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/BEPEventCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) CustomCommands(ctx context.Context, in *CustomCommandsReq, opts ...grpc.CallOption) (*CustomCommandsRes, error) {
	out := new(CustomCommandsRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/CustomCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ExecuteCustomCommand(ctx context.Context, in *ExecuteCustomCommandReq, opts ...grpc.CallOption) (*ExecuteCustomCommandRes, error) {
	out := new(ExecuteCustomCommandRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/ExecuteCustomCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) PostBuildHook(ctx context.Context, in *PostBuildHookReq, opts ...grpc.CallOption) (*PostBuildHookRes, error) {
	out := new(PostBuildHookRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/PostBuildHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) PostTestHook(ctx context.Context, in *PostTestHookReq, opts ...grpc.CallOption) (*PostTestHookRes, error) {
	out := new(PostTestHookRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/PostTestHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) PostRunHook(ctx context.Context, in *PostRunHookReq, opts ...grpc.CallOption) (*PostRunHookRes, error) {
	out := new(PostRunHookRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/PostRunHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Setup(ctx context.Context, in *SetupReq, opts ...grpc.CallOption) (*SetupRes, error) {
	out := new(SetupRes)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	BEPEventCallback(context.Context, *BEPEventCallbackReq) (*BEPEventCallbackRes, error)
	CustomCommands(context.Context, *CustomCommandsReq) (*CustomCommandsRes, error)
	ExecuteCustomCommand(context.Context, *ExecuteCustomCommandReq) (*ExecuteCustomCommandRes, error)
	PostBuildHook(context.Context, *PostBuildHookReq) (*PostBuildHookRes, error)
	PostTestHook(context.Context, *PostTestHookReq) (*PostTestHookRes, error)
	PostRunHook(context.Context, *PostRunHookReq) (*PostRunHookRes, error)
	Setup(context.Context, *SetupReq) (*SetupRes, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) BEPEventCallback(context.Context, *BEPEventCallbackReq) (*BEPEventCallbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BEPEventCallback not implemented")
}
func (*UnimplementedPluginServer) CustomCommands(context.Context, *CustomCommandsReq) (*CustomCommandsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomCommands not implemented")
}
func (*UnimplementedPluginServer) ExecuteCustomCommand(context.Context, *ExecuteCustomCommandReq) (*ExecuteCustomCommandRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCustomCommand not implemented")
}
func (*UnimplementedPluginServer) PostBuildHook(context.Context, *PostBuildHookReq) (*PostBuildHookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostBuildHook not implemented")
}
func (*UnimplementedPluginServer) PostTestHook(context.Context, *PostTestHookReq) (*PostTestHookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTestHook not implemented")
}
func (*UnimplementedPluginServer) PostRunHook(context.Context, *PostRunHookReq) (*PostRunHookRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRunHook not implemented")
}
func (*UnimplementedPluginServer) Setup(context.Context, *SetupReq) (*SetupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_BEPEventCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BEPEventCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).BEPEventCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/BEPEventCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).BEPEventCallback(ctx, req.(*BEPEventCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_CustomCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomCommandsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).CustomCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/CustomCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).CustomCommands(ctx, req.(*CustomCommandsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ExecuteCustomCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCustomCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteCustomCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/ExecuteCustomCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteCustomCommand(ctx, req.(*ExecuteCustomCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_PostBuildHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBuildHookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).PostBuildHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/PostBuildHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).PostBuildHook(ctx, req.(*PostBuildHookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_PostTestHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTestHookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).PostTestHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/PostTestHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).PostTestHook(ctx, req.(*PostTestHookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_PostRunHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRunHookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).PostRunHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/PostRunHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).PostRunHook(ctx, req.(*PostRunHookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Setup(ctx, req.(*SetupReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BEPEventCallback",
			Handler:    _Plugin_BEPEventCallback_Handler,
		},
		{
			MethodName: "CustomCommands",
			Handler:    _Plugin_CustomCommands_Handler,
		},
		{
			MethodName: "ExecuteCustomCommand",
			Handler:    _Plugin_ExecuteCustomCommand_Handler,
		},
		{
			MethodName: "PostBuildHook",
			Handler:    _Plugin_PostBuildHook_Handler,
		},
		{
			MethodName: "PostTestHook",
			Handler:    _Plugin_PostTestHook_Handler,
		},
		{
			MethodName: "PostRunHook",
			Handler:    _Plugin_PostRunHook_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _Plugin_Setup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/sdk/v1alpha4/proto/plugin.proto",
}

// PrompterClient is the client API for Prompter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrompterClient interface {
	Run(ctx context.Context, in *PromptRunReq, opts ...grpc.CallOption) (*PromptRunRes, error)
}

type prompterClient struct {
	cc grpc.ClientConnInterface
}

func NewPrompterClient(cc grpc.ClientConnInterface) PrompterClient {
	return &prompterClient{cc}
}

func (c *prompterClient) Run(ctx context.Context, in *PromptRunReq, opts ...grpc.CallOption) (*PromptRunRes, error) {
	out := new(PromptRunRes)
	err := c.cc.Invoke(ctx, "/proto.Prompter/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrompterServer is the server API for Prompter service.
type PrompterServer interface {
	Run(context.Context, *PromptRunReq) (*PromptRunRes, error)
}

// UnimplementedPrompterServer can be embedded to have forward compatible implementations.
type UnimplementedPrompterServer struct {
}

func (*UnimplementedPrompterServer) Run(context.Context, *PromptRunReq) (*PromptRunRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterPrompterServer(s *grpc.Server, srv PrompterServer) {
	s.RegisterService(&_Prompter_serviceDesc, srv)
}

func _Prompter_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrompterServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Prompter/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrompterServer).Run(ctx, req.(*PromptRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prompter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Prompter",
	HandlerType: (*PrompterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Prompter_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/sdk/v1alpha4/proto/plugin.proto",
}
