/*
Copyright © 2021 Aspect Build Systems

Not licensed for re-use
*/

package outputs

import (
	"aspect.build/cli/pkg/aspect/outputs"
	"aspect.build/cli/pkg/bazel"
	"aspect.build/cli/pkg/interceptors"
	"aspect.build/cli/pkg/ioutils"
	"context"
	"github.com/spf13/cobra"
)

func NewDefaultOutputsCmd() *cobra.Command {
	return NewOutputsCommand(ioutils.DefaultStreams, bazel.New())
}

func NewOutputsCommand(streams ioutils.Streams, bzl bazel.Bazel) *cobra.Command {
	q := outputs.New(streams, bzl, true)

	cmd := &cobra.Command{
		Use:   "outputs",
		Short: "Inspect declared outputs.",
		Long:  "Queries for the outputs declared by actions generated by the given target.",
		RunE: interceptors.Run(
			[]interceptors.Interceptor{
				interceptors.WorkspaceRootInterceptor(),
			},
			func(ctx context.Context, cmd *cobra.Command, args []string) (exitErr error) {
				workspaceRoot := ctx.Value(interceptors.WorkspaceRootKey).(string)
				bzl.SetWorkspaceRoot(workspaceRoot)
				return q.Run(args, bzl)
			},
		),
	}

	return cmd
}
