//! Single-file bridge between the runtime (TaskLike / FeatureLike) and Clap.
//!
//! Public surface:
//!
//! * [`Cmd`] — value-passing input. Holds task & feature trait objects plus
//!   filesystem context. `build()` produces the Clap [`Command`]. `dispatch()`
//!   turns parsed [`ArgMatches`] into a [`Dispatch`]. `print_feature_help()`
//!   renders `aspect feature [<name>]`, the discovery surface for feature flags
//!   (which are hidden from each task's `--help`).
//! * [`Dispatch`] — carries `task_id`, `task_name`, `task_friendly_name`, `task_uuid`, and the parsed
//!   matches. `task_args(...)` and `feature_args(...)` produce the merged
//!   runtime [`Arguments`] for a given task or feature.
//!
//! Everything else in this module is private.

use std::collections::{BTreeMap, HashSet};
use std::path::Path;
use std::process::ExitCode;

use aspect_telemetry::cargo_pkg_display_version;
use axl_runtime::banner;
use axl_runtime::color;
use axl_runtime::diag;
use axl_runtime::engine::arg::Arg;
use axl_runtime::engine::arguments::Arguments;
use axl_runtime::engine::feature::FeatureLike;
use axl_runtime::engine::names::to_display_name;
use axl_runtime::engine::task::{MAX_TASK_GROUPS, TaskLike};
use axl_runtime::eval::TimingMode;
use axl_runtime::module::Mod;
use clap::builder::{PossibleValuesParser, Resettable, StyledStr};
use clap::parser::ValueSource;
use clap::{Arg as ClapArg, ArgAction, ArgMatches, Command, value_parser};
use starlark::collections::SmallMap;
use starlark::values::list::{AllocList, ListRef};
use starlark::values::none::NoneType;
use starlark::values::{Heap, Value, ValueLike};
use thiserror::Error;

const TASK_ID_KEY: &str = "@@@$'__AXL_TASK_ID__'$@@@";
/// `aspect feature [<name>]`: routed to the feature-help renderer in `main`.
const FEATURE_COMMAND: &str = "feature";
/// `aspect describe`: routed to the machine-readable surface dump in `main`.
const DESCRIBE_COMMAND: &str = "describe";
/// Top-level command names `main` intercepts before task parsing; a top-level
/// task of any of these kinds would be unreachable, so it is rejected at build
/// time (see `Tree::insert`). Reachable when nested under a group.
const RESERVED_TOP_LEVEL_COMMANDS: &[&str] = &[
    FEATURE_COMMAND,
    DESCRIBE_COMMAND,
    crate::credential_helper::GET_COMMAND,
];
const TASK_COMMAND_DISPLAY_ORDER: usize = 0;
const TASK_GROUP_DISPLAY_ORDER: usize = 1;

#[derive(Error, Debug)]
pub enum CmdError {
    #[error("task {0:?} (defined in {1:?}) cannot have more than {2} group levels")]
    TooManyGroups(String, String, usize),
    #[error("task {0:?} in group {1:?} (defined in {2:?}) conflicts with another task or group")]
    NameConflict(String, Vec<String>, String),
    #[error(
        "task {0:?} (defined in {1:?}) uses the reserved command name {2:?}; \
         rename it or nest it under a group"
    )]
    ReservedName(String, String, String),
    #[error("no task selected")]
    NoTaskSelected,
}

/// Bridge from runtime values (tasks, features, modules) to a parsed Clap surface.
pub struct Cmd<'a, 'v> {
    pub tasks: Vec<&'v dyn TaskLike<'v>>,
    pub features: Vec<&'v dyn FeatureLike<'v>>,
    pub aspect_root: &'a Path,
    pub modules: &'a [Mod],
}

/// Carries the parsed CLI state needed to execute the selected task and its features.
pub struct Dispatch {
    pub task_id: usize,
    pub task_name: String,
    /// Whether `task_name` carries real meaning — explicitly set (`--task:name`
    /// / `--task-key`) or CI-job-derived — vs a local autogenerated placeholder.
    /// Drives whether the task header surfaces the name alongside the kind.
    pub task_name_meaningful: bool,
    pub task_friendly_name: Option<String>,
    pub task_uuid: Option<String>,
    pub timing: TimingMode,
    matches: ArgMatches,
}

impl<'a, 'v> Cmd<'a, 'v> {
    /// Build the full root Clap command (`aspect`) with all task subcommands.
    pub fn build(&self, version: &str) -> Result<Command, CmdError> {
        let feature_blocks: Vec<FeatureBlock> = self
            .features
            .iter()
            .filter_map(|f| feature_block(*f))
            .collect();

        let cli_header = banner::line(version);

        let mut tree = Tree::default();
        for (idx, task) in self.tasks.iter().enumerate() {
            let label = defined_in_label(task.path(), self.aspect_root, self.modules);
            let task_cmd = task_command(idx, *task, &label, &feature_blocks, &cli_header);
            tree.insert(*task, &label, task_cmd)?;
        }

        let group_section = group_section(&tree.group_rows());
        let root = Command::new("aspect")
            .bin_name("aspect")
            .about("Aspect's programmable task runner built on top of Bazel\n{ Correct, Fast, Usable } -- Choose three")
            .subcommand_value_name("TASK|GROUP|COMMAND")
            .disable_help_subcommand(true)
            // Display only; `version` stays the bare number for AXL and telemetry.
            .version(cargo_pkg_display_version())
            .disable_version_flag(true)
            .arg(
                ClapArg::new("version")
                    .short('v')
                    .long("version")
                    .action(ArgAction::Version)
                    .help("Print version"),
            )
            .arg(
                ClapArg::new("task:name")
                    .long("task:name")
                    .value_name("NAME")
                    .global(true)
                    .value_parser(parse_task_name)
                    .help("A short name uniquely identifying this task invocation. Allowed characters: A-Za-z0-9, _, -. Useful when the same task runs multiple times in one pipeline (e.g. 'backend', 'frontend'). Defaults to '<kind>-<suffix>' if not set."),
            )
            .arg(
                ClapArg::new("task:friendly-name")
                    .long("task:friendly-name")
                    .value_name("FRIENDLY_NAME")
                    .global(true)
                    .help("A human-readable label for this task invocation, shown on status surfaces. Defaults to --task:name."),
            )
            .arg(
                ClapArg::new("task-key")
                    .long("task-key")
                    .value_name("KEY")
                    .global(true)
                    .hide(true)
                    .value_parser(parse_task_name)
                    .help("Deprecated alias for --task:name; will be removed in a future release."),
            )
            .arg(
                ClapArg::new("task:id")
                    .long("task:id")
                    .value_name("UUID")
                    .global(true)
                    .value_parser(parse_task_uuid)
                    .help("A UUID uniquely identifying this task invocation. Auto-generated if not set."),
            )
            .arg(
                ClapArg::new("task:timing-summary")
                    .long("task:timing-summary")
                    .value_name("LEVEL")
                    .global(true)
                    .value_parser(parse_timing_mode)
                    .default_value("detailed")
                    .help("Verbosity of the phase-timing breakdown trailing the task completion line: 'none' (no timing summary), 'total' (total only), 'short' (inline phases), or 'detailed' (multi-line with descriptions; default)."),
            )
            .subcommand(
                // `feature` is not a task: its parsing exists only so `main`
                // can route to `Cmd::print_feature_help`. Disable clap's auto
                // help flag (otherwise `feature --help` renders clap's own
                // help, leaking the global `--task:*` args) and accept a no-op
                // `-h`/`--help` so it falls through to our renderer instead.
                Command::new("feature")
                    .about("List features and show a feature's flags")
                    .hide(true)
                    .disable_help_flag(true)
                    .arg(
                        ClapArg::new("name")
                            .value_name("NAME")
                            .required(false),
                    )
                    .arg(
                        ClapArg::new("help")
                            .short('h')
                            .long("help")
                            .action(ArgAction::SetTrue)
                            .hide(true),
                    ),
            )
            .subcommand(
                // `describe` is not a task: parsing exists only so `main` can
                // route to `Cmd::print_describe`. The whole point is that a
                // reader with no prior knowledge of this repo can enumerate the
                // surface in one call, so it defaults to JSON rather than
                // requiring the flag to be known up front.
                Command::new(DESCRIBE_COMMAND)
                    .about("Print the resolved task, flag and feature surface as JSON")
                    .hide(true)
                    .arg(
                        ClapArg::new("task")
                            .value_name("TASK")
                            .required(false)
                            .help("Describe one task in full, e.g. `aspect describe 'cache diff'`. Omit for the index."),
                    )
                    .arg(
                        ClapArg::new("output")
                            .long("output")
                            .short('o')
                            .value_name("FORMAT")
                            .default_value("json")
                            .value_parser(PossibleValuesParser::new(["json"]))
                            .help("Output format."),
                    ),
            )
            .subcommand(Command::new("version").about("Print version").hide(true))
            .subcommand(
                Command::new("help")
                    .about("Print this message or the help of the given subcommand(s)")
                    .hide(true),
            )
            .help_template(format!(
                "{cli_header}\n\n{{about-with-newline}}\n{{usage-heading}} {{usage}}\n\n\x1b[1;4mTasks:\x1b[0m\n{{subcommands}}{group_section}\n\x1b[1;4mCommands:\x1b[0m\n  \x1b[1mdescribe\x1b[0m  Print the resolved task, flag and feature surface as JSON\n  \x1b[1mfeature\x1b[0m   List features and their flags\n  \x1b[1mversion\x1b[0m   Print version\n  \x1b[1mhelp\x1b[0m      Print this message or the help of the given subcommand(s)\n\n\x1b[1;4mOptions:\x1b[0m\n{{options}}"
            ));

        tree.attach(root, version)
    }

    /// Walk the parsed matches to the deepest subcommand and extract task ids + uuids.
    pub fn dispatch(&self, matches: ArgMatches) -> Result<Dispatch, CmdError> {
        let leaf = deepest_subcommand(&matches).ok_or(CmdError::NoTaskSelected)?;
        let task_id = *leaf
            .get_one::<usize>(TASK_ID_KEY)
            .ok_or(CmdError::NoTaskSelected)?;
        // Resolution order: --task:name wins; the deprecated --task-key is
        // accepted as an alias and always warns; otherwise the name defaults
        // to the task kind (the deepest selected subcommand name).
        let explicit_name = leaf
            .get_one::<String>("task:name")
            .filter(|s| !s.is_empty())
            .cloned();
        let deprecated_key = leaf
            .get_one::<String>("task-key")
            .filter(|s| !s.is_empty())
            .cloned();
        if deprecated_key.is_some() {
            diag::warn(
                "--task-key is deprecated; use --task:name instead. \
                 --task-key will be removed in a future release.",
            );
        }
        // An explicit name (`--task:name` / `--task-key`) is meaningful as-is.
        // Otherwise auto-generate: `<kind>-<ci-job>` on CI (de-duped per
        // run/machine, meaningful), else `<kind>-<random-suffix>` (a local
        // placeholder, not meaningful).
        let (task_name, task_name_meaningful) = match explicit_name.or(deprecated_key) {
            Some(name) => (name, true),
            None => {
                let kind = leaf_command_name(&matches).unwrap_or_default();
                let auto = axl_runtime::ci::auto_task_name(&kind, generate_name_suffix);
                (auto.name, auto.meaningful)
            }
        };
        let task_friendly_name = leaf.get_one::<String>("task:friendly-name").cloned();
        let task_uuid = leaf.get_one::<String>("task:id").cloned();
        let timing = leaf
            .get_one::<TimingMode>("task:timing-summary")
            .copied()
            .unwrap_or_default();
        Ok(Dispatch {
            task_id,
            task_name,
            task_name_meaningful,
            task_friendly_name,
            task_uuid,
            timing,
            matches,
        })
    }

    /// Render `aspect feature [<name>]` and return the process exit code.
    ///
    /// With no name, lists every active feature (keyed by the kebab slug the
    /// user passes back in). With a name, prints just that feature's flags. An
    /// unknown name lists the valid ones on stderr and exits 2.
    /// Print the resolved surface as JSON (`aspect describe`).
    ///
    /// Pretty-printed rather than compact: the output is read far more often
    /// than it is piped into another program, and diffs of it are useful.
    pub fn print_describe(&self, version: &str, task: Option<&str>) -> ExitCode {
        let doc = match task {
            None => describe_index(version, &self.tasks, &self.features),
            Some(name) => {
                let full = describe_json(
                    version,
                    &self.tasks,
                    &self.features,
                    self.aspect_root,
                    self.modules,
                );
                match select_task(&full, name) {
                    Some(t) => t,
                    None => {
                        eprintln!(
                            "error: no task {name:?}. Run `aspect describe` for the list of commands."
                        );
                        return ExitCode::FAILURE;
                    }
                }
            }
        };
        match serde_json::to_string_pretty(&doc) {
            Ok(s) => {
                println!("{s}");
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("error: failed to serialize the CLI surface: {e}");
                ExitCode::FAILURE
            }
        }
    }

    pub fn print_feature_help(&self, version: &str, name: Option<&str>) -> ExitCode {
        let mut blocks: Vec<(&dyn FeatureLike<'_>, FeatureBlock)> = self
            .features
            .iter()
            .filter_map(|f| feature_block(*f).map(|b| (*f, b)))
            .collect();
        blocks.sort_by(|(a, _), (b, _)| a.name().cmp(&b.name()));

        match name {
            None => {
                print!(
                    "{}",
                    render_feature_list(version, &blocks, color::stdout_supports_color())
                );
                ExitCode::SUCCESS
            }
            Some(name) => match blocks.iter().find(|(f, _)| f.name() == name) {
                Some((feat, block)) => {
                    render_feature_detail(version, *feat, block, self.aspect_root, self.modules)
                        .print_help()
                        .ok();
                    ExitCode::SUCCESS
                }
                None => {
                    let valid: Vec<String> = blocks.iter().map(|(f, _)| f.name()).collect();
                    eprintln!(
                        "\x1b[1;31merror:\x1b[0m unknown feature {name:?}. Valid features: {}",
                        valid.join(", ")
                    );
                    ExitCode::from(2)
                }
            },
        }
    }
}

impl Dispatch {
    /// Build the merged `Arguments` for the selected task.
    pub fn task_args<'v>(&self, task: &dyn TaskLike<'v>, heap: Heap<'v>) -> Arguments<'v> {
        let leaf = deepest_subcommand(&self.matches).expect("dispatch built from valid matches");
        merge_args(task.args(), task.overrides(), leaf, heap, Scope::Task)
    }

    /// Build the merged `Arguments` for a feature implementation invocation.
    pub fn feature_args<'v>(&self, feat: &dyn FeatureLike<'v>, heap: Heap<'v>) -> Arguments<'v> {
        let leaf = deepest_subcommand(&self.matches).expect("dispatch built from valid matches");
        let prefix = feat.name();
        merge_args(
            feat.args(),
            feat.overrides(),
            leaf,
            heap,
            Scope::Feature(&prefix),
        )
    }
}

// ── Scope: how an arg's Clap key is derived ────────────────────────────────

#[derive(Copy, Clone)]
enum Scope<'a> {
    Task,
    Feature(&'a str),
}

fn clap_id(scope: Scope<'_>, name: &str, arg: &Arg) -> String {
    match scope {
        Scope::Task => name.to_owned(),
        // Always prefixed, even under a `long` override: task arg IDs are bare
        // names, so a prefixed feature ID can never collide with one — only the
        // *long flag* can, and `task_command` resolves that by skipping the
        // feature arg on tasks whose own args already claim the flag.
        Scope::Feature(prefix) => {
            let long = arg
                .long_override()
                .map(str::to_owned)
                .unwrap_or_else(|| name.replace('_', "-"));
            if prefix.is_empty() {
                long
            } else {
                format!("{}:{}", prefix, long)
            }
        }
    }
}

fn long_flag(scope: Scope<'_>, name: &str, arg: &Arg) -> String {
    if let Some(lo) = arg.long_override() {
        return lo.to_owned();
    }
    match scope {
        Scope::Task => name.replace('_', "-"),
        Scope::Feature(prefix) => {
            let long = name.replace('_', "-");
            if prefix.is_empty() {
                long
            } else {
                format!("{}:{}", prefix, long)
            }
        }
    }
}

// ── Arg → ClapArg ──────────────────────────────────────────────────────────

fn arg_to_clap(scope: Scope<'_>, name: &str, arg: &Arg) -> ClapArg {
    let id = clap_id(scope, name, arg);
    let long = long_flag(scope, name, arg);
    match arg {
        Arg::String {
            required,
            default,
            short,
            values,
            description,
            bare,
            ..
        } => {
            let mut it = ClapArg::new(id.clone())
                .long(long.clone())
                .value_name(long)
                .short(short_char(short))
                .help(help_text(description))
                .required(*required)
                .default_value(default.clone());
            it = if let Some(values) = values {
                it.value_parser(PossibleValuesParser::new(values))
            } else {
                it.value_parser(value_parser!(String))
            };
            // `bare = "…"` makes a valueless `--flag` legal. `require_equals` keeps
            // the next argv token from being swallowed as the value, so
            // `--remote //foo` parses as bare flag + target rather than
            // `--remote=//foo` (same shape as the Boolean arm below).
            if let Some(bare) = bare {
                it = it
                    .num_args(0..=1)
                    .require_equals(true)
                    .default_missing_value(bare.clone());
            }
            it
        }
        Arg::Boolean {
            required,
            default,
            short,
            description,
            ..
        } => ClapArg::new(id)
            .long(long.clone())
            .value_name(long)
            .short(short_char(short))
            .help(help_text(description))
            .required(*required)
            .default_value(if *default { "true" } else { "false" })
            .value_parser(value_parser!(bool))
            .num_args(0..=1)
            .require_equals(true)
            .default_missing_value("true"),
        Arg::Int {
            required,
            default,
            short,
            description,
            ..
        } => ClapArg::new(id)
            .long(long.clone())
            .value_name(long)
            .short(short_char(short))
            .help(help_text(description))
            .required(*required)
            .default_value(default.to_string())
            .value_parser(value_parser!(i32)),
        Arg::UInt {
            required,
            default,
            short,
            description,
            ..
        } => ClapArg::new(id)
            .long(long.clone())
            .value_name(long)
            .short(short_char(short))
            .help(help_text(description))
            .required(*required)
            .default_value(default.to_string())
            .value_parser(value_parser!(u32)),
        Arg::Positional {
            minimum,
            maximum,
            default,
            description,
        } => {
            let mut it = ClapArg::new(id.clone())
                .value_parser(value_parser!(String))
                .value_name(id)
                .help(help_text(description))
                .num_args(*minimum as usize..=*maximum as usize);
            if let Some(default) = default {
                it = it.default_values(default);
            }
            it
        }
        Arg::TrailingVarArgs { description } => ClapArg::new(id.clone())
            .value_parser(value_parser!(String))
            .value_name(id)
            .help(help_text(description))
            .allow_hyphen_values(true)
            .last(true)
            .num_args(0..),
        Arg::StringList {
            required,
            default,
            short,
            description,
            ..
        } => {
            let mut it = ClapArg::new(id)
                .long(long.clone())
                .value_name(long)
                .short(short_char(short))
                .help(help_text(description))
                .action(ArgAction::Append)
                .required(*required)
                .value_parser(value_parser!(String));
            if !default.is_empty() {
                it = it.default_values(default.iter().cloned());
            }
            it
        }
        Arg::BooleanList {
            required,
            default,
            short,
            description,
            ..
        } => {
            let mut it = ClapArg::new(id)
                .long(long.clone())
                .value_name(long)
                .short(short_char(short))
                .help(help_text(description))
                .action(ArgAction::Append)
                .required(*required)
                .value_parser(value_parser!(bool))
                .num_args(0..=1)
                .default_missing_value("true");
            if !default.is_empty() {
                it = it.default_values(default.iter().map(|&b| if b { "true" } else { "false" }));
            }
            it
        }
        Arg::IntList {
            required,
            default,
            short,
            description,
            ..
        } => {
            let mut it = ClapArg::new(id)
                .long(long.clone())
                .value_name(long)
                .short(short_char(short))
                .help(help_text(description))
                .action(ArgAction::Append)
                .required(*required)
                .value_parser(value_parser!(i32));
            if !default.is_empty() {
                it = it.default_values(default.iter().map(|i| i.to_string()));
            }
            it
        }
        Arg::UIntList {
            required,
            default,
            short,
            description,
            ..
        } => {
            let mut it = ClapArg::new(id)
                .long(long.clone())
                .value_name(long)
                .short(short_char(short))
                .help(help_text(description))
                .action(ArgAction::Append)
                .required(*required)
                .value_parser(value_parser!(u32));
            if !default.is_empty() {
                it = it.default_values(default.iter().map(|u| u.to_string()));
            }
            it
        }
        Arg::Custom { .. } => unreachable!("Custom args are not CLI-exposed"),
    }
}

// Apply a config.axl override to the just-built ClapArg: sets the default and
// drops `required` (the user has supplied the value, just not on the CLI).
fn with_override(mut clap_arg: ClapArg, arg: &Arg, override_strings: &[String]) -> ClapArg {
    clap_arg = match arg {
        Arg::StringList { .. }
        | Arg::BooleanList { .. }
        | Arg::IntList { .. }
        | Arg::UIntList { .. }
        | Arg::TrailingVarArgs { .. } => clap_arg.default_values(override_strings.iter().cloned()),
        _ => {
            if let Some(v) = override_strings.first() {
                clap_arg.default_value(v.clone())
            } else {
                clap_arg
            }
        }
    };
    clap_arg.required(false)
}

// ── Match → Arguments merge ────────────────────────────────────────────────

fn merge_args<'v>(
    schema: &SmallMap<String, Arg>,
    overrides_value: Value<'v>,
    matches: &ArgMatches,
    heap: Heap<'v>,
    scope: Scope<'_>,
) -> Arguments<'v> {
    let args = Arguments::new();
    for (name, arg) in schema.iter() {
        match arg {
            Arg::Custom { default, .. } => {
                let v = default
                    .map(|fv| fv.to_value())
                    .unwrap_or_else(|| heap.alloc(NoneType));
                args.insert(name.clone(), v);
            }
            cli => {
                let key = clap_id(scope, name, cli);
                // A feature arg loses its Clap registration on task commands
                // whose own args claim its long flag (see `task_command`); fall
                // back to the schema default there.
                if matches.try_contains_id(&key).is_err() {
                    if let Some(val) = schema_default_value(cli, heap) {
                        args.insert(name.clone(), val);
                    }
                    continue;
                }
                if let Some(val) = clap_to_value(cli, &key, matches, heap) {
                    args.insert(name.clone(), val);
                }
                // Track CLI-explicit keys so `ctx.args.is_explicit(name)`
                // can tell defaults from user-typed values downstream.
                if matches.value_source(&key) == Some(ValueSource::CommandLine) {
                    args.mark_explicit(name.clone());
                }
            }
        }
    }

    // Layer config.axl overrides for keys the user did NOT pass on the CLI.
    let Some(overrides) = overrides_value.downcast_ref::<Arguments>() else {
        return args;
    };
    for (k, v) in overrides.entries() {
        let user_explicit = schema
            .get(&k)
            .filter(|a| a.is_cli_exposed())
            .map(|a| {
                let key = clap_id(scope, &k, a);
                matches.try_contains_id(&key).is_ok()
                    && matches.value_source(&key) == Some(ValueSource::CommandLine)
            })
            .unwrap_or(false);
        if !user_explicit {
            args.insert(k, v);
        }
    }
    args
}

/// The value an arg resolves to when it has no Clap registration at all —
/// the schema default, mirroring what [`clap_to_value`] yields for an
/// untouched flag. `None` for `Custom` (handled by the caller).
fn schema_default_value<'v>(arg: &Arg, heap: Heap<'v>) -> Option<Value<'v>> {
    Some(match arg {
        Arg::Custom { .. } => return None,
        Arg::String { default, .. } => heap.alloc_str(default).to_value(),
        Arg::Boolean { default, .. } => heap.alloc(*default),
        Arg::Int { default, .. } => heap.alloc(*default).to_value(),
        Arg::UInt { default, .. } => heap.alloc(*default).to_value(),
        Arg::Positional { default, .. } => {
            heap.alloc(AllocList(default.clone().unwrap_or_default()))
        }
        Arg::TrailingVarArgs { .. } => heap.alloc(AllocList(Vec::<String>::new())),
        Arg::StringList { default, .. } => heap.alloc(AllocList(default.clone())),
        Arg::BooleanList { default, .. } => heap.alloc(AllocList(default.clone())),
        Arg::IntList { default, .. } => heap.alloc(AllocList(default.clone())),
        Arg::UIntList { default, .. } => heap.alloc(AllocList(default.clone())),
    })
}

fn clap_to_value<'v>(
    arg: &Arg,
    key: &str,
    matches: &ArgMatches,
    heap: Heap<'v>,
) -> Option<Value<'v>> {
    let v = match arg {
        Arg::Custom { .. } => return None,
        Arg::String { .. } => heap
            .alloc_str(matches.get_one::<String>(key).unwrap_or(&String::new()))
            .to_value(),
        Arg::Int { .. } => heap
            .alloc(*matches.get_one::<i32>(key).unwrap_or(&0))
            .to_value(),
        Arg::UInt { .. } => heap
            .alloc(*matches.get_one::<u32>(key).unwrap_or(&0))
            .to_value(),
        Arg::Boolean { .. } => heap.alloc(*matches.get_one::<bool>(key).unwrap_or(&false)),
        Arg::Positional { .. } | Arg::TrailingVarArgs { .. } => heap.alloc(AllocList(
            matches
                .get_many::<String>(key)
                .map_or(vec![], |it| it.map(|s| s.as_str()).collect()),
        )),
        Arg::StringList { .. } => heap.alloc(AllocList(
            matches
                .get_many::<String>(key)
                .unwrap_or_default()
                .map(|s| s.as_str())
                .collect::<Vec<_>>(),
        )),
        Arg::BooleanList { .. } => heap.alloc(AllocList(
            matches
                .get_many::<bool>(key)
                .unwrap_or_default()
                .copied()
                .collect::<Vec<_>>(),
        )),
        Arg::IntList { .. } => heap.alloc(AllocList(
            matches
                .get_many::<i32>(key)
                .unwrap_or_default()
                .copied()
                .collect::<Vec<_>>(),
        )),
        Arg::UIntList { .. } => heap.alloc(AllocList(
            matches
                .get_many::<u32>(key)
                .unwrap_or_default()
                .copied()
                .collect::<Vec<_>>(),
        )),
    };
    Some(v)
}

// ── Override stringification (for Clap default_value) ──────────────────────

fn stringify_overrides(
    overrides_value: Value<'_>,
) -> std::collections::HashMap<String, Vec<String>> {
    let Some(args) = overrides_value.downcast_ref::<Arguments>() else {
        return std::collections::HashMap::new();
    };
    args.entries()
        .into_iter()
        .map(|(k, v)| {
            let elements = if let Some(list) = ListRef::from_value(v) {
                list.iter().map(stringify_value).collect()
            } else {
                vec![stringify_value(v)]
            };
            (k, elements)
        })
        .collect()
}

fn stringify_value(v: Value<'_>) -> String {
    if let Some(s) = v.unpack_str() {
        return s.to_owned();
    }
    let s = v.to_string();
    if v.get_type() == "bool" {
        s.to_lowercase()
    } else {
        s
    }
}

// ── Per-feature help block ─────────────────────────────────────────────────
//
// Built once per feature. Each task command registers these args hidden (so
// they parse but don't clutter `--help`); `aspect feature [<name>]` renders
// them for discovery via `Cmd::print_feature_help`.

struct FeatureBlock {
    args: Vec<(String, Arg)>,
    heading: String,
    prefix: String,
}

fn feature_block(feat: &dyn FeatureLike<'_>) -> Option<FeatureBlock> {
    let mut args: Vec<(String, Arg)> = feat
        .args()
        .iter()
        .filter(|(_, v)| v.is_cli_exposed())
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    if args.is_empty() {
        return None;
    }

    // Bake config.axl overrides into the schema defaults so `--help` shows them.
    for (k, vals) in stringify_overrides(feat.overrides()) {
        let Some((_, arg)) = args.iter_mut().find(|(name, _)| name == &k) else {
            continue;
        };
        let Some(first) = vals.first() else { continue };
        match arg {
            Arg::Boolean { default, .. } => *default = first == "true",
            Arg::String { default, .. } => *default = first.clone(),
            Arg::Int { default, .. } => {
                if let Ok(v) = first.parse() {
                    *default = v;
                }
            }
            Arg::UInt { default, .. } => {
                if let Ok(v) = first.parse() {
                    *default = v;
                }
            }
            _ => {}
        }
    }

    let heading = format!("{} Options", feat.display_name());
    Some(FeatureBlock {
        args,
        heading,
        prefix: feat.name(),
    })
}

// ── `aspect describe` rendering ────────────────────────────────────────────

/// One CLI argument, described by the flag string a caller would actually type.
///
/// `scope` decides that string: task args are bare kebab (`--scope`), feature
/// args carry their feature prefix (`--tips:silence`). Both go through
/// [`long_flag`], the same helper that builds the real Clap arg, so what is
/// described and what parses cannot drift.
fn describe_arg(scope: Scope<'_>, name: &str, arg: &Arg) -> serde_json::Value {
    use serde_json::json;

    let flag = match arg {
        Arg::Positional { .. } | Arg::TrailingVarArgs { .. } => None,
        _ => Some(format!("--{}", long_flag(scope, name, arg))),
    };
    let (kind, default, values, description, short) = match arg {
        Arg::String {
            default,
            values,
            description,
            short,
            ..
        } => ("string", json!(default), json!(values), description, short),
        Arg::Boolean {
            default,
            description,
            short,
            ..
        } => ("boolean", json!(default), json!(null), description, short),
        Arg::Int {
            default,
            description,
            short,
            ..
        } => ("int", json!(default), json!(null), description, short),
        Arg::UInt {
            default,
            description,
            short,
            ..
        } => ("uint", json!(default), json!(null), description, short),
        Arg::StringList {
            default,
            description,
            short,
            ..
        } => (
            "string_list",
            json!(default),
            json!(null),
            description,
            short,
        ),
        Arg::BooleanList {
            default,
            description,
            short,
            ..
        } => (
            "boolean_list",
            json!(default),
            json!(null),
            description,
            short,
        ),
        Arg::IntList {
            default,
            description,
            short,
            ..
        } => ("int_list", json!(default), json!(null), description, short),
        Arg::UIntList {
            default,
            description,
            short,
            ..
        } => ("uint_list", json!(default), json!(null), description, short),
        Arg::Positional {
            default,
            description,
            ..
        } => (
            "positional",
            json!(default),
            json!(null),
            description,
            &None,
        ),
        Arg::TrailingVarArgs { description } => (
            "trailing_var_args",
            json!(null),
            json!(null),
            description,
            &None,
        ),
        // Filtered out by `is_cli_exposed` before reaching here.
        Arg::Custom { description, .. } => ("custom", json!(null), json!(null), description, &None),
    };
    // `Arg::is_required` reports false for positionals — they carry cardinality
    // instead of a `required` flag — so a `minimum = 1` positional would read as
    // optional. Derive requiredness from the cardinality and report the bounds,
    // or a caller cannot tell `aspect run` (exactly one target) from a task that
    // takes none.
    let (required, minimum, maximum) = match arg {
        Arg::Positional {
            minimum, maximum, ..
        } => (*minimum >= 1, json!(minimum), json!(maximum)),
        _ => (arg.is_required(), json!(null), json!(null)),
    };
    json!({
        "name": name,
        "type": kind,
        "flag": flag,
        "short": short.as_ref().map(|s| format!("-{s}")),
        "required": required,
        "minimum": minimum,
        "maximum": maximum,
        "default": default,
        "allowed_values": values,
        "description": description,
    })
}

/// Re-type a `config.axl` override for the JSON `default` field.
///
/// [`stringify_overrides`] flattens every override to `Vec<String>` for Clap's
/// benefit. Handing that back verbatim would describe an int default as
/// `["2"]`, so scalars collapse to a single value parsed back to the arg's own
/// type and only genuine list args stay arrays.
fn override_as_default(arg: &Arg, over: &[String]) -> serde_json::Value {
    use serde_json::json;

    match arg {
        // Positional values are genuinely strings (target patterns), so they
        // stay as they came.
        Arg::StringList { .. } | Arg::Positional { .. } => json!(over),
        Arg::BooleanList { .. } => json!(over.iter().map(|v| v == "true").collect::<Vec<_>>()),
        Arg::IntList { .. } | Arg::UIntList { .. } => json!(
            over.iter()
                .map(|v| v
                    .parse::<i64>()
                    .map(|n| json!(n))
                    .unwrap_or_else(|_| json!(v)))
                .collect::<Vec<_>>()
        ),
        _ => match over.first() {
            None => json!(null),
            Some(first) => match arg {
                Arg::Boolean { .. } => json!(first == "true"),
                Arg::Int { .. } | Arg::UInt { .. } => first
                    .parse::<i64>()
                    .map(|n| json!(n))
                    .unwrap_or_else(|_| json!(first)),
                _ => json!(first),
            },
        },
    }
}

/// Every runnable command with its summary, and nothing else.
fn describe_index(
    version: &str,
    tasks: &[&dyn TaskLike<'_>],
    features: &[&dyn FeatureLike<'_>],
) -> serde_json::Value {
    use serde_json::json;

    let mut commands: Vec<serde_json::Value> = tasks
        .iter()
        .map(|task| {
            let mut path = task.group().clone();
            path.push(task.kind());
            json!({
                "command": format!("aspect {}", path.join(" ")),
                "summary": task.summary(),
            })
        })
        .collect();
    commands.sort_by(|a, b| a["command"].as_str().cmp(&b["command"].as_str()));

    json!({
        "aspect_cli_version": version,
        "commands": commands,
        "features": features.iter().map(|f| f.name()).collect::<Vec<_>>(),
        "next": {
            "task_detail": "aspect describe '<command without the leading `aspect `>' — e.g. aspect describe 'cache diff'",
            "feature_flags": "aspect feature <name>",
        },
    })
}

/// Pull one task out of a full [`describe_json`] document by its command path,
/// with or without the leading `aspect `.
fn select_task(full: &serde_json::Value, name: &str) -> Option<serde_json::Value> {
    let want = name.trim().trim_start_matches("aspect ").trim();
    full["tasks"].as_array()?.iter().find_map(|t| {
        let cmd = t["command"].as_str()?;
        (cmd.trim_start_matches("aspect ") == want).then(|| t.clone())
    })
}

/// The full resolved surface as JSON: every task reachable in this repo, the
/// flags each accepts, and the feature flags accepted everywhere.
///
/// This exists because the Aspect surface is per-repo — a caller cannot know
/// what `aspect <task>` means here without asking. One call answers it.
fn describe_json(
    version: &str,
    tasks: &[&dyn TaskLike<'_>],
    features: &[&dyn FeatureLike<'_>],
    aspect_root: &Path,
    modules: &[Mod],
) -> serde_json::Value {
    use serde_json::json;

    let described_tasks: Vec<serde_json::Value> = tasks
        .iter()
        .map(|task| {
            let kind = task.kind();
            let mut path = task.group().clone();
            path.push(kind.clone());
            let overrides = stringify_overrides(task.overrides());
            let args: Vec<serde_json::Value> = task
                .cli_args()
                .into_iter()
                .map(|(arg_name, arg)| {
                    let mut described = describe_arg(Scope::Task, arg_name, arg);
                    // A config.axl override is what the caller will actually
                    // get, so report it as the default and say where it came
                    // from rather than showing the unreachable schema value.
                    if let Some(over) = overrides.get(arg_name)
                        && let Some(obj) = described.as_object_mut()
                    {
                        obj.insert("default".into(), override_as_default(arg, over));
                        obj.insert("default_from_config".into(), json!(true));
                    }
                    described
                })
                .collect();
            json!({
                "command": format!("aspect {}", path.join(" ")),
                "path": path,
                "name": kind,
                "summary": task.summary(),
                "description": task.description(),
                "defined_in": defined_in_label(task.path(), aspect_root, modules),
                "args": args,
            })
        })
        .collect();

    let described_features: Vec<serde_json::Value> = features
        .iter()
        .filter_map(|feat| {
            let block = feature_block(*feat)?;
            // `feature_block` bakes scalar overrides into its schema but skips
            // list-valued ones, so re-apply them here for the same reason task
            // args do it: a caller must see the default execution will use, not
            // one it can never observe.
            let overrides = stringify_overrides(feat.overrides());
            let flags: Vec<serde_json::Value> = block
                .args
                .iter()
                .map(|(arg_name, arg)| {
                    let mut described = describe_arg(Scope::Feature(&block.prefix), arg_name, arg);
                    if let Some(over) = overrides.get(arg_name)
                        && let Some(obj) = described.as_object_mut()
                    {
                        obj.insert("default".into(), override_as_default(arg, over));
                        obj.insert("default_from_config".into(), json!(true));
                    }
                    described
                })
                .collect();
            Some(json!({
                "name": feat.name(),
                "summary": feat.summary(),
                "description": feat.description(),
                "defined_in": defined_in_label(feat.path(), aspect_root, modules),
                "flags": flags,
            }))
        })
        .collect();

    json!({
        "aspect_cli_version": version,
        "tasks": described_tasks,
        "features": described_features,
    })
}

// ── `aspect feature` rendering ─────────────────────────────────────────────

/// Render the `aspect feature` listing: one row per feature, keyed by the
/// kebab slug the user passes to `aspect feature <name>`, with its summary.
fn render_feature_list(
    version: &str,
    blocks: &[(&dyn FeatureLike<'_>, FeatureBlock)],
    color: bool,
) -> String {
    let width = blocks
        .iter()
        .map(|(f, _)| f.name().len())
        .max()
        .unwrap_or(0);
    let (bold, bold_underline, reset) = if color {
        ("\x1b[1m", "\x1b[1;4m", "\x1b[0m")
    } else {
        ("", "", "")
    };
    let mut out = format!(
        "{}\n\n{bold_underline}Features:{reset}\n",
        banner::line_colored(version, color)
    );
    for (feat, _) in blocks {
        let slug = feat.name();
        let pad = " ".repeat(width - slug.len() + 2);
        out.push_str(&format!(
            "  {bold}{}{reset}{}{}\n",
            slug,
            pad,
            feat.summary()
        ));
    }
    out.push_str("\nRun `aspect feature <NAME>` to see a feature's flags.\n");
    out
}

/// Build the `aspect feature <name>` help command: the feature's prose (or its
/// "defined in" line when it has none) above its flags, rendered with the same
/// clap formatting the flags used to get inline in each task's `--help`.
fn render_feature_detail(
    version: &str,
    feat: &dyn FeatureLike<'_>,
    block: &FeatureBlock,
    aspect_root: &Path,
    modules: &[Mod],
) -> Command {
    let context = format!(
        "\x1b[3m{}\x1b[0m feature defined in \x1b[3m{}\x1b[0m",
        feat.export_name().unwrap_or_default(),
        defined_in_label(feat.path(), aspect_root, modules),
    );
    let body = if !feat.description().is_empty() {
        feat.description()
    } else {
        feat.summary()
    };
    let about = if body.is_empty() {
        context
    } else {
        format!("{body}\n\n{context}")
    };
    let mut cmd = Command::new(format!("feature {}", feat.name()))
        .no_binary_name(true)
        .disable_help_flag(true)
        .help_template(format!(
            "{}\n\n{about}\n\n{{all-args}}",
            banner::line(version)
        ));
    for (arg_name, arg) in block.args.iter() {
        cmd = cmd.arg(
            arg_to_clap(Scope::Feature(&block.prefix), arg_name, arg)
                .help_heading(block.heading.clone()),
        );
    }
    cmd
}

// ── Per-task subcommand assembly ───────────────────────────────────────────

fn task_command(
    index: usize,
    task: &dyn TaskLike<'_>,
    label: &str,
    feature_blocks: &[FeatureBlock],
    cli_header: &str,
) -> Command {
    let kind = task.kind();
    let friendly_kind = task.friendly_kind();
    let display = if !friendly_kind.is_empty() {
        friendly_kind
    } else {
        to_display_name(&kind)
    };

    let context_line = format!(
        "\x1b[3m{}\x1b[0m task defined in \x1b[3m{}\x1b[0m",
        kind, label,
    );
    let about = if task.summary().is_empty() {
        if needs_summary_warning(task.summary(), label) {
            warn_missing_summary(&kind, label);
        }
        context_line.clone()
    } else {
        task.summary().clone()
    };
    let help_header = if task.summary().is_empty() && task.description().is_empty() {
        None
    } else {
        let body = if !task.description().is_empty() {
            task.description().clone()
        } else {
            task.summary().clone()
        };
        Some(format!("{}\n\n{}", body, context_line))
    };

    let mut cmd = Command::new(kind)
        .about(about)
        .display_order(TASK_COMMAND_DISPLAY_ORDER)
        .arg(
            ClapArg::new(TASK_ID_KEY)
                .long(TASK_ID_KEY)
                .hide(true)
                .hide_default_value(true)
                .hide_short_help(true)
                .hide_possible_values(true)
                .hide_long_help(true)
                .value_parser(value_parser!(usize))
                .default_value(index.to_string()),
        );

    let overrides = stringify_overrides(task.overrides());
    let heading = format!("{} Options", display);
    for (arg_name, arg) in task.cli_args() {
        let mut clap_arg = arg_to_clap(Scope::Task, arg_name, arg).help_heading(heading.clone());
        if let Some(over) = overrides.get(arg_name) {
            clap_arg = with_override(clap_arg, arg, over);
        }
        cmd = cmd.arg(clap_arg);
    }

    // Feature flags stay parseable on the task command but are hidden from
    // `--help`; `aspect feature [<name>]` surfaces them instead (see the footer
    // appended to the help template below).
    //
    // A task's own args win any collision: a feature arg whose long flag matches
    // a task arg's name or long (e.g. a `long`-overridden `--deployment` vs the
    // auth tasks' `deployment`) is not registered here — `merge_args` then falls
    // back to the feature arg's schema default, leaving the feature inert on
    // that task rather than panicking on a duplicate Clap arg.
    let claimed: HashSet<String> = task
        .cli_args()
        .into_iter()
        .flat_map(|(arg_name, arg)| [arg_name.to_owned(), long_flag(Scope::Task, arg_name, arg)])
        .collect();
    for block in feature_blocks {
        for (arg_name, arg) in block.args.iter() {
            if claimed.contains(&long_flag(Scope::Feature(&block.prefix), arg_name, arg)) {
                continue;
            }
            let clap_arg = arg_to_clap(Scope::Feature(&block.prefix), arg_name, arg).hide(true);
            cmd = cmd.arg(clap_arg);
        }
    }

    // Always use a custom template so the grey "Aspect CLI v… — docs URL"
    // header lands at the top. When the task supplies its own help_header
    // body (summary/description), use that as the about block; otherwise
    // fall back to clap's `{about-with-newline}`.
    let about_block = match help_header {
        Some(h) => format!("{h}\n"),
        None => "{about-with-newline}".to_string(),
    };
    let feature_footer = "\x1b[2mFeatures add CI reporting and artifact integrations \
         (GitHub, Buildkite, GitLab, CircleCI, telemetry). Their flags are accepted here \
         but hidden; run `aspect feature` to list them.\x1b[0m";
    cmd = cmd.help_template(format!(
        "{cli_header}\n\n{about_block}\n{{usage-heading}} {{usage}}\n\n{{all-args}}\n\n{feature_footer}"
    ));
    cmd
}

// ── Subgroup tree ──────────────────────────────────────────────────────────

#[derive(Default)]
struct Tree {
    subgroups: BTreeMap<String, Tree>,
    tasks: BTreeMap<String, Command>,
}

impl Tree {
    fn insert(
        &mut self,
        task: &dyn TaskLike<'_>,
        label: &str,
        cmd: Command,
    ) -> Result<(), CmdError> {
        let group = task.group().clone();
        if group.len() > MAX_TASK_GROUPS {
            return Err(CmdError::TooManyGroups(
                task.kind(),
                label.to_owned(),
                MAX_TASK_GROUPS,
            ));
        }
        // `main` routes these top-level commands before task parsing, so a
        // top-level task of the same kind would never run. Reject it rather than
        // let it silently disappear; nested under a group it is reachable.
        if group.is_empty() && RESERVED_TOP_LEVEL_COMMANDS.contains(&task.kind().as_str()) {
            return Err(CmdError::ReservedName(
                task.kind(),
                label.to_owned(),
                task.kind(),
            ));
        }
        self.insert_at(&task.kind(), &group[..], &group[..], label, cmd)
    }

    fn insert_at(
        &mut self,
        name: &str,
        full_group: &[String],
        remaining: &[String],
        label: &str,
        cmd: Command,
    ) -> Result<(), CmdError> {
        if remaining.is_empty() {
            if self.subgroups.contains_key(name) || self.tasks.contains_key(name) {
                return Err(CmdError::NameConflict(
                    name.to_owned(),
                    full_group.to_vec(),
                    label.to_owned(),
                ));
            }
            self.tasks.insert(name.to_owned(), cmd);
            return Ok(());
        }
        let head = &remaining[0];
        if self.tasks.contains_key(head) {
            return Err(CmdError::NameConflict(
                head.clone(),
                full_group.to_vec(),
                label.to_owned(),
            ));
        }
        let sub = self.subgroups.entry(head.clone()).or_default();
        sub.insert_at(name, full_group, &remaining[1..], label, cmd)
    }

    /// What each subgroup contains, as a comma-joined list of its task kinds
    /// and nested group names. A group has no summary of its own to show, and
    /// "auth task group" tells a reader nothing about whether the command they
    /// want is inside — listing the members does.
    fn group_rows(&self) -> Vec<(String, String)> {
        self.subgroups
            .iter()
            .map(|(name, sub)| (name.clone(), sub.member_list()))
            .collect()
    }

    fn member_list(&self) -> String {
        let mut members: Vec<String> = self.tasks.keys().cloned().collect();
        members.extend(self.subgroups.keys().map(|g| format!("{g}/")));
        elide(&members, MEMBER_LIST_WIDTH)
    }

    fn attach(self, mut root: Command, version: &str) -> Result<Command, CmdError> {
        // Subgroups (rendered hidden, with their own help template).
        let header = banner::line(version);
        for (name, sub) in self.subgroups {
            let sub_rows = sub.group_rows();
            let about = format!("\x1b[3m{}\x1b[0m: {}", name, sub.member_list());
            let mut template =
                format!("{header}\n\n{{about-with-newline}}\n{{usage-heading}} {{usage}}");
            if !sub.tasks.is_empty() {
                template.push_str("\n\n\x1b[1;4mTasks:\x1b[0m\n{subcommands}");
            }
            template.push_str(&group_section(&sub_rows));
            let template = format!(
                "{}\n\n\x1b[1;4mOptions:\x1b[0m\n{{options}}",
                template.trim_end()
            );
            let mut subcmd = Command::new(name.clone())
                .subcommand_value_name("TASK|GROUP")
                .about(about)
                .display_order(TASK_GROUP_DISPLAY_ORDER)
                .hide(true)
                .help_template(template);
            subcmd = sub.attach(subcmd, version)?;
            if root.find_subcommand(&name).is_some() {
                return Err(CmdError::NameConflict(name, vec![], String::new()));
            }
            root = root.subcommand(subcmd);
        }
        // Leaf task subcommands.
        for (name, subcmd) in self.tasks {
            if root.find_subcommand(&name).is_some() {
                return Err(CmdError::NameConflict(name, vec![], String::new()));
            }
            root = root.subcommand(subcmd);
        }
        if root.get_subcommands().next().is_some() {
            root = root.arg_required_else_help(true);
        }
        Ok(root)
    }
}

/// Width budget for a group's member list before it is elided.
const MEMBER_LIST_WIDTH: usize = 58;

/// Join `items`, trimming to `width` and appending `…` plus the count dropped.
fn elide(items: &[String], width: usize) -> String {
    let mut out = String::new();
    for (i, item) in items.iter().enumerate() {
        let sep = if i == 0 { "" } else { ", " };
        if !out.is_empty() && out.len() + sep.len() + item.len() > width {
            return format!("{out}, … (+{} more)", items.len() - i);
        }
        out.push_str(sep);
        out.push_str(item);
    }
    out
}

fn group_section(rows: &[(String, String)]) -> String {
    if rows.is_empty() {
        return String::new();
    }
    let max_len = rows.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
    let mut s = String::from("\n\n\x1b[1;4mTask Groups:\x1b[0m\n");
    for (name, members) in rows {
        let pad = " ".repeat(max_len - name.len() + 2);
        s.push_str(&format!("  \x1b[1m{}\x1b[0m{}{}\n", name, pad, members));
    }
    s
}

// ── Misc helpers ───────────────────────────────────────────────────────────

/// Warn that a task has no `summary`, which will become required.
fn warn_missing_summary(kind: &str, defined_in: &str) {
    diag::warn(&format!(
        "task {kind:?} in {defined_in} has no summary, so it shows as \
         \"{kind} task defined in {defined_in}\" in `aspect --help`. \
         Add summary = \"…\" to task(...) — this becomes an error in a future release."
    ));
}

/// Undocumented, and defined in this repo rather than a module (`@mod//…`) —
/// a module's task is not the reader's to fix.
fn needs_summary_warning(summary: &str, defined_in: &str) -> bool {
    summary.is_empty() && !defined_in.starts_with('@')
}

fn defined_in_label(path: &Path, aspect_root: &Path, modules: &[Mod]) -> String {
    for r#mod in modules {
        if r#mod.is_root() || !path.starts_with(&r#mod.root) {
            continue;
        }
        let rel = path.strip_prefix(&r#mod.root).unwrap_or(path);
        return format!("@{}//{}", r#mod.name, rel.display());
    }
    let rel = path.strip_prefix(aspect_root).unwrap_or(path);
    format!("{}", rel.display())
}

fn deepest_subcommand(matches: &ArgMatches) -> Option<&ArgMatches> {
    let (_, mut leaf) = matches.subcommand()?;
    while let Some((_, next)) = leaf.subcommand() {
        leaf = next;
    }
    Some(leaf)
}

/// The deepest selected subcommand's name — the task kind (`build`, `test`, …),
/// used as the default task name when neither `--task:name` nor `--task-key`
/// is given.
fn leaf_command_name(matches: &ArgMatches) -> Option<String> {
    let (mut name, mut leaf) = matches.subcommand()?;
    while let Some((next_name, next)) = leaf.subcommand() {
        name = next_name;
        leaf = next;
    }
    Some(name.to_owned())
}

fn parse_task_name(s: &str) -> Result<String, String> {
    if s.chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        Ok(s.to_owned())
    } else {
        Err(format!(
            "'{}' contains invalid characters (allowed: A-Za-z0-9, _, -)",
            s
        ))
    }
}

/// A friendly random suffix (e.g. "fluffy-parakeet") appended to the task kind
/// to form a default `--task:name`. Falls back to a short UUID fragment.
fn generate_name_suffix() -> String {
    names::Generator::with_naming(names::Name::Plain)
        .next()
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string()[..8].to_string())
}

fn parse_task_uuid(s: &str) -> Result<String, String> {
    uuid::Uuid::parse_str(s)
        .map(|u| u.to_string())
        .map_err(|_| {
            format!(
                "'{}' is not a valid UUID (expected xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
                s
            )
        })
}

fn parse_timing_mode(s: &str) -> Result<TimingMode, String> {
    s.parse::<TimingMode>()
}

fn help_text(description: &Option<String>) -> Resettable<StyledStr> {
    match description {
        Some(text) => Resettable::Value(text.into()),
        None => Resettable::Reset,
    }
}

fn short_char(short: &Option<String>) -> Resettable<char> {
    match short {
        Some(text) => Resettable::Value(text.chars().next().unwrap().into()),
        None => Resettable::Reset,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axl_runtime::engine::arg::Arg;
    use starlark::collections::SmallMap;
    use starlark::values::FrozenValue;
    use std::path::PathBuf;
    use std::sync::OnceLock;

    static EMPTY: OnceLock<String> = OnceLock::new();
    fn empty_string() -> &'static String {
        EMPTY.get_or_init(String::new)
    }

    struct StubTask {
        name: String,
        group: Vec<String>,
        args: SmallMap<String, Arg>,
        path: PathBuf,
        summary: String,
    }

    impl<'v> TaskLike<'v> for StubTask {
        fn args(&self) -> &SmallMap<String, Arg> {
            &self.args
        }
        fn summary(&self) -> &String {
            &self.summary
        }
        fn description(&self) -> &String {
            empty_string()
        }
        fn friendly_kind(&self) -> String {
            String::new()
        }
        fn group(&self) -> &Vec<String> {
            &self.group
        }
        fn kind(&self) -> String {
            self.name.clone()
        }
        fn path(&self) -> &PathBuf {
            &self.path
        }
        fn overrides(&self) -> Value<'v> {
            FrozenValue::new_none().to_value()
        }
        fn implementation(&self) -> Value<'v> {
            unimplemented!("test stub")
        }
        fn trait_type_ids(&self) -> Vec<u64> {
            vec![]
        }
        fn trait_values(&self) -> Vec<starlark::values::Value<'v>> {
            vec![]
        }
    }

    /// Summary is non-empty so `Cmd::build` doesn't warn in every test.
    fn stub_task(name: &str, group: &[&str], args: SmallMap<String, Arg>) -> StubTask {
        StubTask {
            name: name.to_owned(),
            group: group.iter().map(|s| s.to_string()).collect(),
            args,
            path: PathBuf::from("/repo/tasks/test.axl"),
            summary: format!("Stub {name} task."),
        }
    }

    fn arg_string(default: &str) -> Arg {
        Arg::String {
            required: false,
            default: default.to_owned(),
            short: None,
            long: None,
            values: None,
            description: None,
            bare: None,
        }
    }

    fn arg_string_with_long(default: &str, long: &str) -> Arg {
        Arg::String {
            required: false,
            default: default.to_owned(),
            short: None,
            long: Some(long.to_owned()),
            values: None,
            description: None,
            bare: None,
        }
    }

    struct StubFeature {
        name: String,
        export_name: String,
        display_name: String,
        summary: String,
        args: SmallMap<String, Arg>,
        path: PathBuf,
    }

    impl<'v> FeatureLike<'v> for StubFeature {
        fn name(&self) -> String {
            self.name.clone()
        }
        fn export_name(&self) -> Option<String> {
            Some(self.export_name.clone())
        }
        fn summary(&self) -> &String {
            &self.summary
        }
        fn description(&self) -> &String {
            empty_string()
        }
        fn display_name(&self) -> String {
            self.display_name.clone()
        }
        fn args(&self) -> &SmallMap<String, Arg> {
            &self.args
        }
        fn path(&self) -> &PathBuf {
            &self.path
        }
        fn overrides(&self) -> Value<'v> {
            FrozenValue::new_none().to_value()
        }
        fn implementation(&self) -> Value<'v> {
            unimplemented!("test stub")
        }
    }

    /// Builds a feature carrying a single `enabled` boolean arg. `identifier` is
    /// the CamelCase export name (e.g. `"ArtifactUpload"`); name/display_name are
    /// derived to match production (`artifact-upload` / `Artifact Upload`).
    fn stub_feature(identifier: &str) -> StubFeature {
        stub_feature_with_summary(identifier, "")
    }

    fn stub_feature_with_summary(identifier: &str, summary: &str) -> StubFeature {
        let mut args: SmallMap<String, Arg> = SmallMap::new();
        args.insert(
            "enabled".to_owned(),
            Arg::Boolean {
                required: false,
                default: true,
                short: None,
                long: None,
                description: None,
            },
        );
        feature_with_args(identifier, summary, args)
    }

    fn feature_with_args(
        identifier: &str,
        summary: &str,
        args: SmallMap<String, Arg>,
    ) -> StubFeature {
        StubFeature {
            name: axl_runtime::engine::names::to_command_name(identifier),
            export_name: identifier.to_owned(),
            display_name: axl_runtime::engine::names::camel_to_display_name(identifier),
            summary: summary.to_owned(),
            args,
            path: PathBuf::from("/repo/feature/artifact_upload.axl"),
        }
    }

    // ── Cmd::build ─────────────────────────────────────────────────────────

    #[test]
    fn build_renders_a_task_subcommand() {
        let mut args: SmallMap<String, Arg> = SmallMap::new();
        args.insert("greeting".to_owned(), arg_string("hello"));
        let t = stub_task("greet", &[], args);
        let cmd = Cmd {
            tasks: vec![&t as &dyn TaskLike],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        assert!(root.find_subcommand("greet").is_some());
    }

    #[test]
    fn build_groups_tasks_under_subcommand() {
        let t1 = stub_task("a", &["dev"], SmallMap::new());
        let t2 = stub_task("b", &["dev"], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t1, &t2],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let dev = root.find_subcommand("dev").expect("dev group present");
        assert!(dev.find_subcommand("a").is_some());
        assert!(dev.find_subcommand("b").is_some());
    }

    /// The identity banner (version + docs URL) is woven into the help
    /// template of the root command, each task subcommand, and each task
    /// group — so it shows on every `--help` screen.
    #[test]
    fn build_puts_identity_banner_on_every_help_screen() {
        let t = stub_task("greet", &["dev"], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let mut root = cmd.build("1.2.3").expect("build ok");

        // `banner::line` marks debug builds, and tests always build with debug
        // assertions on, so derive the suffix rather than hardcoding the whole line.
        let debug = if aspect_telemetry::is_debug_build() {
            " (debug build)"
        } else {
            ""
        };
        let banner = format!("Aspect CLI v1.2.3{debug} — https://aspect.build/docs/cli");
        let banner = banner.as_str();
        let rendered = |c: &mut Command| c.render_help().to_string();

        assert!(
            rendered(&mut root).contains(banner),
            "root help missing banner"
        );

        let dev = root.find_subcommand_mut("dev").expect("dev group present");
        assert!(rendered(dev).contains(banner), "group help missing banner");

        let greet = dev
            .find_subcommand_mut("greet")
            .expect("greet task present");
        assert!(rendered(greet).contains(banner), "task help missing banner");
    }

    #[test]
    fn build_rejects_duplicate_task_names() {
        let t1 = stub_task("dup", &[], SmallMap::new());
        let t2 = stub_task("dup", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t1, &t2],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        match cmd.build("0.0.0") {
            Err(CmdError::NameConflict(name, ..)) => assert_eq!(name, "dup"),
            other => panic!("expected NameConflict, got {:?}", other),
        }
    }

    #[test]
    fn build_rejects_top_level_task_named_get() {
        let t = stub_task(crate::credential_helper::GET_COMMAND, &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        match cmd.build("0.0.0") {
            Err(CmdError::ReservedName(name, ..)) => {
                assert_eq!(name, crate::credential_helper::GET_COMMAND);
            }
            other => panic!("expected ReservedName, got {:?}", other),
        }
    }

    #[test]
    fn build_allows_get_task_nested_in_group() {
        // Bazel only invokes the bare `aspect get`, so `aspect dev get` is fine.
        let t = stub_task(
            crate::credential_helper::GET_COMMAND,
            &["dev"],
            SmallMap::new(),
        );
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let dev = root.find_subcommand("dev").expect("dev group present");
        assert!(
            dev.find_subcommand(crate::credential_helper::GET_COMMAND)
                .is_some()
        );
    }

    #[test]
    fn build_rejects_top_level_task_named_feature() {
        let t = stub_task(FEATURE_COMMAND, &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        match cmd.build("0.0.0") {
            Err(CmdError::ReservedName(name, ..)) => assert_eq!(name, FEATURE_COMMAND),
            other => panic!("expected ReservedName, got {:?}", other),
        }
    }

    #[test]
    fn build_allows_feature_task_nested_in_group() {
        let t = stub_task(FEATURE_COMMAND, &["dev"], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let dev = root.find_subcommand("dev").expect("dev group present");
        assert!(dev.find_subcommand(FEATURE_COMMAND).is_some());
    }

    // ── Feature flags: hidden from task help, parseable, listed by `feature` ──

    /// A feature's flags are registered on each task (so they still parse) but
    /// hidden from the task's `--help`; only the task's own "<Task> Options"
    /// section and a discovery footer remain.
    #[test]
    fn feature_flags_are_hidden_from_task_help() {
        let mut task_args: SmallMap<String, Arg> = SmallMap::new();
        task_args.insert("greeting".to_owned(), arg_string("hello"));
        let t = stub_task("greet", &[], task_args);
        let f = stub_feature("ArtifactUpload");
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![&f as &dyn FeatureLike],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let mut root = cmd.build("0.0.0").expect("build ok");
        let mut greet = root
            .find_subcommand_mut("greet")
            .expect("greet present")
            .clone();
        let help = greet.render_help().to_string();
        assert!(help.contains("Greet Options"), "task section missing");
        assert!(
            !help.contains("Artifact Upload Options"),
            "feature section should be hidden from task help"
        );
        assert!(
            !help.contains("artifact-upload:enabled"),
            "feature flag should be hidden from task help"
        );
        assert!(
            help.contains("aspect feature"),
            "discovery footer missing from task help"
        );
        // Hidden ≠ removed: the flag is still a registered arg on the command.
        assert!(
            greet
                .get_arguments()
                .any(|a| a.get_id() == "artifact-upload:enabled"),
            "feature flag should still be parseable on the task"
        );
    }

    #[test]
    fn feature_list_is_sorted_by_slug_with_summaries() {
        let tips = stub_feature_with_summary("Tips", "Collect tips.");
        let au = stub_feature_with_summary("ArtifactUpload", "Upload artifacts.");
        let blocks: Vec<(&dyn FeatureLike, FeatureBlock)> = [&au, &tips]
            .iter()
            .map(|f| (*f as &dyn FeatureLike, feature_block(*f).unwrap()))
            .collect();
        let mut sorted = blocks;
        sorted.sort_by(|(a, _), (b, _)| a.name().cmp(&b.name()));
        let out = render_feature_list("1.2.3", &sorted, true);
        let au_at = out.find("artifact-upload").expect("artifact-upload listed");
        let tips_at = out.find("tips").expect("tips listed");
        assert!(au_at < tips_at, "rows should be alphabetical by slug");
        assert!(out.contains("Upload artifacts."), "summary missing");
        assert!(out.contains("aspect feature <NAME>"), "footer missing");
    }

    #[test]
    fn describe_emits_runnable_commands_and_real_flag_strings() {
        let mut args: SmallMap<String, Arg> = SmallMap::new();
        args.insert("base_ref".to_owned(), arg_string("main"));
        args.insert(
            "targets".to_owned(),
            Arg::Positional {
                minimum: 0,
                maximum: 8,
                default: Some(vec!["//...".to_owned()]),
                description: None,
            },
        );
        let task = stub_task("login", &["auth"], args);
        let tasks: Vec<&dyn TaskLike> = vec![&task];

        let doc = describe_json("1.2.3", &tasks, &[], Path::new("/repo"), &[]);
        let t = &doc["tasks"][0];

        // The command string is the whole point: an agent copies it verbatim.
        assert_eq!(t["command"], "aspect auth login");
        assert_eq!(t["path"], serde_json::json!(["auth", "login"]));
        assert_eq!(doc["aspect_cli_version"], "1.2.3");

        let by_name = |n: &str| {
            t["args"]
                .as_array()
                .unwrap()
                .iter()
                .find(|a| a["name"] == n)
                .unwrap()
                .clone()
        };
        // `_` becomes `-` in the flag, matching what Clap actually parses.
        assert_eq!(by_name("base_ref")["flag"], "--base-ref");
        assert_eq!(by_name("base_ref")["default"], "main");
        // Positionals have no flag to type.
        assert_eq!(by_name("targets")["flag"], serde_json::Value::Null);
        assert_eq!(by_name("targets")["type"], "positional");
        // A flag arg carries no cardinality.
        assert_eq!(by_name("base_ref")["minimum"], serde_json::Value::Null);
    }

    #[test]
    fn summary_warning_fires_only_for_undocumented_first_party_tasks() {
        assert!(needs_summary_warning("", ".aspect/deploy.axl"));

        assert!(!needs_summary_warning(
            "Deploy the app.",
            ".aspect/deploy.axl"
        ));
        assert!(!needs_summary_warning("Build it.", "@aspect//build.axl"));
        assert!(!needs_summary_warning("", "@aspect//build.axl"));
        assert!(!needs_summary_warning("", "@some_third_party//task.axl"));
    }

    /// The runtime warning skips `@aspect//` tasks, so enforce the rule here.
    ///
    /// Reads the `include_dir!` embed, not the filesystem, so it works under
    /// Bazel's sandbox where the cargo layout isn't on disk.
    #[test]
    fn every_builtin_task_declares_a_summary() {
        use include_dir::{Dir, include_dir};
        static ASPECT_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/src/builtins/aspect");

        let mut offenders = Vec::new();
        for f in ASPECT_DIR.find("**/*.axl").unwrap() {
            let Some(text) = f.as_file().and_then(|file| file.contents_utf8()) else {
                continue;
            };
            // `<var> = task(` at column 0, keywords at one indent.
            for (idx, _) in text.match_indices(" = task(\n") {
                let body = &text[idx..];
                let end = body.find("\n)").unwrap_or(body.len());
                if !body[..end].contains("\n    summary = ") {
                    let line = text[..idx].lines().count() + 1;
                    offenders.push(format!("{}:{}", f.path().display(), line));
                }
            }
        }

        assert!(
            offenders.is_empty(),
            "built-in tasks must declare a summary; add `summary = \"…\"` at:\n  {}",
            offenders.join("\n  ")
        );
    }

    #[test]
    fn describe_reports_positional_cardinality_and_derives_requiredness() {
        let mut args: SmallMap<String, Arg> = SmallMap::new();
        // `Arg::is_required` returns false for every positional, so a required
        // one is only distinguishable via its cardinality.
        args.insert(
            "target".to_owned(),
            Arg::Positional {
                minimum: 1,
                maximum: 1,
                default: None,
                description: None,
            },
        );
        args.insert(
            "extras".to_owned(),
            Arg::Positional {
                minimum: 0,
                maximum: 8,
                default: None,
                description: None,
            },
        );
        let task = stub_task("run", &[], args);
        let tasks: Vec<&dyn TaskLike> = vec![&task];
        let doc = describe_json("1.2.3", &tasks, &[], Path::new("/repo"), &[]);
        let by_name = |n: &str| {
            doc["tasks"][0]["args"]
                .as_array()
                .unwrap()
                .iter()
                .find(|a| a["name"] == n)
                .unwrap()
                .clone()
        };

        assert_eq!(by_name("target")["required"], true);
        assert_eq!(by_name("target")["minimum"], 1);
        assert_eq!(by_name("target")["maximum"], 1);

        assert_eq!(by_name("extras")["required"], false);
        assert_eq!(by_name("extras")["minimum"], 0);
        assert_eq!(by_name("extras")["maximum"], 8);
    }

    #[test]
    fn describe_retypes_config_overrides_rather_than_stringifying_them() {
        let int_arg = Arg::Int {
            required: false,
            default: 1,
            short: None,
            long: None,
            description: None,
        };
        assert_eq!(
            override_as_default(&int_arg, &["2".to_owned()]),
            serde_json::json!(2)
        );

        let bool_arg = Arg::Boolean {
            required: false,
            default: false,
            short: None,
            long: None,
            description: None,
        };
        assert_eq!(
            override_as_default(&bool_arg, &["true".to_owned()]),
            serde_json::json!(true)
        );

        // Genuine list args keep their array shape.
        let list_arg = Arg::StringList {
            required: false,
            default: vec![],
            short: None,
            long: None,
            description: None,
        };
        assert_eq!(
            override_as_default(&list_arg, &["a".to_owned(), "b".to_owned()]),
            serde_json::json!(["a", "b"])
        );

        // …and numeric lists are re-typed elementwise, not left as strings.
        let int_list = Arg::IntList {
            required: false,
            default: vec![],
            short: None,
            long: None,
            description: None,
        };
        assert_eq!(
            override_as_default(&int_list, &["1".to_owned(), "2".to_owned()]),
            serde_json::json!([1, 2])
        );

        // Positional values are target patterns — genuinely strings.
        let positional = Arg::Positional {
            minimum: 0,
            maximum: 8,
            default: None,
            description: None,
        };
        assert_eq!(
            override_as_default(&positional, &["//...".to_owned()]),
            serde_json::json!(["//..."])
        );
    }

    #[test]
    fn feature_detail_renders_flags_and_defined_in_line() {
        let f = stub_feature("ArtifactUpload");
        let block = feature_block(&f).unwrap();
        let help = render_feature_detail("1.2.3", &f, &block, Path::new("/repo"), &[])
            .render_help()
            .to_string();
        assert!(help.contains("Artifact Upload Options"), "heading missing");
        assert!(help.contains("artifact-upload:enabled"), "flag missing");
        assert!(
            help.contains("ArtifactUpload feature defined in"),
            "defined-in line missing"
        );
    }

    #[test]
    fn print_feature_help_exit_codes() {
        let f = stub_feature("ArtifactUpload");
        let cmd = Cmd {
            tasks: vec![],
            features: vec![&f as &dyn FeatureLike],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        assert_eq!(cmd.print_feature_help("0.0.0", None), ExitCode::SUCCESS);
        assert_eq!(
            cmd.print_feature_help("0.0.0", Some("artifact-upload")),
            ExitCode::SUCCESS
        );
        assert_eq!(
            cmd.print_feature_help("0.0.0", Some("nope")),
            ExitCode::from(2)
        );
    }

    // ── Dispatch ───────────────────────────────────────────────────────────

    #[test]
    fn dispatch_extracts_task_id_and_key() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--task:name=smoke"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        assert_eq!(dispatch.task_id, 0);
        assert_eq!(dispatch.task_name, "smoke");
        assert!(dispatch.task_uuid.is_none());
    }

    #[test]
    fn dispatch_defaults_task_name_to_kind_with_suffix_when_absent() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        // Auto-named as `<kind>-<suffix>`; the suffix is random so assert the prefix.
        assert!(
            dispatch.task_name.starts_with("greet-"),
            "expected greet-<suffix>, got {}",
            dispatch.task_name
        );
        assert!(dispatch.task_name.len() > "greet-".len());
    }

    #[test]
    fn dispatch_accepts_deprecated_task_key() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--task-key=legacy"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        assert_eq!(dispatch.task_name, "legacy");
    }

    #[test]
    fn dispatch_task_name_wins_over_deprecated_task_key() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--task:name=winner", "--task-key=loser"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        assert_eq!(dispatch.task_name, "winner");
    }

    #[test]
    fn dispatch_extracts_friendly_name() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let with = root
            .clone()
            .try_get_matches_from(["aspect", "greet", "--task:friendly-name=My Build"])
            .expect("parse ok");
        assert_eq!(
            cmd.dispatch(with).expect("dispatch ok").task_friendly_name,
            Some("My Build".to_owned())
        );
        let without = root
            .try_get_matches_from(["aspect", "greet"])
            .expect("parse ok");
        assert!(
            cmd.dispatch(without)
                .expect("dispatch ok")
                .task_friendly_name
                .is_none()
        );
    }

    #[test]
    fn dispatch_extracts_task_uuid() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let uuid = "12345678-1234-1234-1234-123456789abc";
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--task:id", uuid])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        assert_eq!(dispatch.task_uuid.as_deref(), Some(uuid));
    }

    #[test]
    fn dispatch_parses_timing_summary() {
        let t = stub_task("greet", &[], SmallMap::new());
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");

        let parse = |args: &[&str]| {
            let matches = root.clone().try_get_matches_from(args);
            matches.map(|m| cmd.dispatch(m).expect("dispatch ok").timing)
        };

        assert_eq!(
            parse(&["aspect", "greet", "--task:timing-summary=short"]).unwrap(),
            TimingMode::Short
        );
        // Default flows from the flag's default_value, not Default::default().
        assert_eq!(parse(&["aspect", "greet"]).unwrap(), TimingMode::Detailed);
        // Invalid level is rejected by the value parser at parse time.
        assert!(parse(&["aspect", "greet", "--task:timing-summary=verbose"]).is_err());
    }

    // ── Override merge (no heap path: no overrides applied) ────────────────

    #[test]
    fn task_args_merges_cli_value() {
        let mut args: SmallMap<String, Arg> = SmallMap::new();
        args.insert("greeting".to_owned(), arg_string("hello"));
        let t = stub_task("greet", &[], args);
        let cmd = Cmd {
            tasks: vec![&t],
            features: vec![],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--greeting=hi"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");

        Heap::temp(|heap| {
            let merged = dispatch.task_args(&t, heap);
            let v = merged.get("greeting").expect("present");
            assert_eq!(v.unpack_str(), Some("hi"));
        });
    }

    #[test]
    fn clap_id_for_task_is_bare_name() {
        let arg = arg_string("");
        assert_eq!(clap_id(Scope::Task, "upload_bucket", &arg), "upload_bucket");
    }

    #[test]
    fn clap_id_for_feature_uses_prefix() {
        let arg = arg_string("");
        assert_eq!(
            clap_id(Scope::Feature("artifact-upload"), "mode", &arg),
            "artifact-upload:mode"
        );
    }

    /// A `long` override changes the flag spelling but NOT the ID's namespace:
    /// the ID stays feature-prefixed so it can never collide with a task arg ID
    /// (only the long flag can, which `task_command` resolves by skipping).
    #[test]
    fn clap_id_for_feature_prefixes_long_override() {
        let arg = Arg::String {
            required: false,
            default: String::new(),
            short: None,
            long: Some("custom-flag".to_owned()),
            values: None,
            description: None,
            bare: None,
        };
        assert_eq!(
            clap_id(Scope::Feature("artifact-upload"), "mode", &arg),
            "artifact-upload:custom-flag"
        );
        assert_eq!(
            long_flag(Scope::Feature("artifact-upload"), "mode", &arg),
            "custom-flag"
        );
    }

    /// A feature arg `long`-overridden to a flag a task already owns (the
    /// `Deployment` feature's `--deployment` vs `auth login --deployment`) must
    /// not shadow or duplicate the task's arg: the task wins, and the feature
    /// falls back to its schema defaults on that command.
    #[test]
    fn feature_long_override_yields_to_task_arg() {
        let mut targs: SmallMap<String, Arg> = SmallMap::new();
        targs.insert("deployment".to_owned(), arg_string(""));
        let t = stub_task("login", &[], targs);

        let mut fargs: SmallMap<String, Arg> = SmallMap::new();
        fargs.insert(
            "deployment".to_owned(),
            arg_string_with_long("", "deployment"),
        );
        fargs.insert("remote".to_owned(), arg_string_with_long("", "remote"));
        let f = feature_with_args("Deployment", "Stub feature.", fargs);

        let cmd = Cmd {
            tasks: vec![&t as &dyn TaskLike],
            features: vec![&f as &dyn FeatureLike],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        // Panics in debug builds without the skip: duplicate `deployment` arg.
        let matches = root
            .try_get_matches_from(["aspect", "login", "--deployment", "prod"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");

        Heap::temp(|heap| {
            let task_args = dispatch.task_args(&t, heap);
            assert_eq!(
                task_args.get("deployment").expect("present").unpack_str(),
                Some("prod")
            );
            let feat_args = dispatch.feature_args(&f, heap);
            // Skipped on this command: schema default, not the task's value.
            assert_eq!(
                feat_args.get("deployment").expect("present").unpack_str(),
                Some("")
            );
            // The non-colliding sibling arg stays registered and readable.
            assert_eq!(
                feat_args.get("remote").expect("present").unpack_str(),
                Some("")
            );
        });
    }

    /// On a task without a colliding arg, the overridden long parses normally
    /// and routes to the feature.
    #[test]
    fn feature_long_override_parses_on_non_colliding_task() {
        let t = stub_task("greet", &[], SmallMap::new());
        let mut fargs: SmallMap<String, Arg> = SmallMap::new();
        fargs.insert("remote".to_owned(), arg_string_with_long("", "remote"));
        let f = feature_with_args("Deployment", "Stub feature.", fargs);
        let cmd = Cmd {
            tasks: vec![&t as &dyn TaskLike],
            features: vec![&f as &dyn FeatureLike],
            aspect_root: Path::new("/repo"),
            modules: &[],
        };
        let root = cmd.build("0.0.0").expect("build ok");
        let matches = root
            .try_get_matches_from(["aspect", "greet", "--remote=exec"])
            .expect("parse ok");
        let dispatch = cmd.dispatch(matches).expect("dispatch ok");
        Heap::temp(|heap| {
            let feat_args = dispatch.feature_args(&f, heap);
            assert_eq!(
                feat_args.get("remote").expect("present").unpack_str(),
                Some("exec")
            );
        });
    }

    /// `args.string(bare = …)` makes a valueless `--flag` legal — what lets `--remote`
    /// stand alone. The `default` must stay reachable so "absent" and "passed bare"
    /// remain distinguishable, and `require_equals` must keep the following argv token
    /// from being eaten as the value (`--remote //foo` is a bare flag plus a target,
    /// not `--remote=//foo`).
    #[test]
    fn string_arg_with_bare_accepts_valueless_flag() {
        let arg = Arg::String {
            required: false,
            default: String::new(),
            short: None,
            long: None,
            values: None,
            description: None,
            bare: Some("default".to_owned()),
        };
        let cmd = || {
            Command::new("t")
                .no_binary_name(true)
                .arg(arg_to_clap(Scope::Task, "remote", &arg))
                .arg(ClapArg::new("targets").num_args(0..))
        };
        let get = |m: &ArgMatches| m.get_one::<String>("remote").cloned().unwrap_or_default();

        // Absent → the default; bare → the `bare` value; explicit → that value.
        assert_eq!(
            get(&cmd().try_get_matches_from([] as [&str; 0]).unwrap()),
            ""
        );
        assert_eq!(
            get(&cmd().try_get_matches_from(["--remote"]).unwrap()),
            "default"
        );
        assert_eq!(
            get(&cmd()
                .try_get_matches_from(["--remote=exec,no-bes"])
                .unwrap()),
            "exec,no-bes"
        );

        // A following positional is not swallowed as the flag's value.
        let m = cmd().try_get_matches_from(["--remote", "//foo"]).unwrap();
        assert_eq!(get(&m), "default");
        assert_eq!(
            m.get_many::<String>("targets")
                .unwrap()
                .cloned()
                .collect::<Vec<_>>(),
            vec!["//foo".to_string()]
        );

        // Space-separated values are rejected rather than silently misparsed.
        assert!(
            Command::new("t")
                .no_binary_name(true)
                .arg(arg_to_clap(Scope::Task, "remote", &arg))
                .try_get_matches_from(["--remote", "exec"])
                .is_err()
        );
    }

    /// Without `bare`, a string flag still requires its value — the pre-existing
    /// behavior every other `args.string` flag depends on.
    #[test]
    fn string_arg_without_bare_still_requires_a_value() {
        let arg = arg_string("");
        assert!(
            Command::new("t")
                .no_binary_name(true)
                .arg(arg_to_clap(Scope::Task, "mode", &arg))
                .try_get_matches_from(["--mode"])
                .is_err()
        );
    }
}
