version: 2.1

workflows:
  aspect-workflows:
    jobs:
      - pre-build
      - build-task:
          requires: [pre-build]
      - test-task:
          requires: [pre-build]
      - delivery-task:
          requires: [pre-build]

jobs:
  pre-build:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - run:
          name: Pre-build CLI
          command: |
            echo "Build and upload CLI to remote cache"
            .aspect/bootstrap.sh

  build-task:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: .aspect/bootstrap.sh
      - run:
          name: Build Task (ASPECT_DEBUG=1)
          command: ASPECT_DEBUG=1 aspect build //...
      - run:
          name: Build Task
          command: aspect build //...

  test-task:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: .aspect/bootstrap.sh
      - run:
          name: Test Task (ASPECT_DEBUG=1)
          command: ASPECT_DEBUG=1 aspect test //...
      - run:
          name: Test Task
          command: aspect test //...

  delivery-task:
    machine: true
    resource_class: aspect-build/aspect-default
    working_directory: /mnt/ephemeral/workdir
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: .aspect/bootstrap.sh
      - run:
          name: Delivery Task (ASPECT_DEBUG=1)
          command: ASPECT_DEBUG=1 aspect delivery --build_url $CIRCLE_BUILD_URL --commit_sha $CIRCLE_SHA1 --force_target //:hello -- //:hello //:hello2
      - run:
          name: Delivery Task
          command: aspect delivery --build_url $CIRCLE_BUILD_URL --commit_sha $CIRCLE_SHA1 --force_target //:hello -- //:hello //:hello2
