version: 2.1

parameters:
  perform_delivery:
    type: boolean
    default: false
  delivery_commit:
    type: string
    default: ''
    description: The commit to checkout and run the delivery from
  delivery_targets:
    type: string
    default: ''
    description: Ignore the target(s) that are listed in the delivery manifest
      and instead deliver these targets. Comma-separated list of labels.

# enable CircleCI's dynamic configuration feature
setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  slack: circleci/slack@4.12.1
  aspect-workflows: aspect-build/workflows@dev:5.8.0-rc14-cci-orb2

jobs:
  legacy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is some legacy non-workflows job"

workflows:
  default:
    jobs:
      - legacy
      - aspect-workflows/setup:
          resource_class: aspect-build/aspect-cli
          context:
            - slack
