version: 2.1

parameters:
  perform_delivery:
    type: boolean
    default: false
  delivery_commit:
    type: string
    default: ''
    description: The commit to checkout and run the delivery from
  delivery_targets:
    type: string
    default: ''
    description: Ignore the target(s) that are listed in the delivery manifest
      and instead deliver these targets. Comma-separated list of labels.

# enable CircleCI's dynamic configuration feature
setup: true

orbs:
  slack: circleci/slack@4.12.1
  aspect-workflows: aspect-build/workflows@dev:5.9.0-beta.10

jobs:
  legacy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "No-op step since CCI requires one step for the job to be valid"
      - when:
          condition:
            and:
              - not:
                  equal: [scheduled_pipeline, << pipeline.trigger_source >>]
          steps:
            - checkout
            - run: echo "This is an example of legacy non-workflows job"

workflows:
  default-workflow:
    jobs:
      - legacy
      - aspect-workflows/setup:
          resource_class: aspect-build/aspect-small-arm64
          context:
            - slack
