version: 2.1

parameters:
  perform_delivery:
    type: boolean
    default: false
  delivery_commit:
    type: string
    default: ''
    description: The commit to checkout and run the delivery from
  delivery_targets:
    type: string
    default: ''
    description: Ignore the target(s) that are listed in the delivery manifest
      and instead deliver these targets. Comma-separated list of labels.

# enable CircleCI's dynamic configuration feature
setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  slack: circleci/slack@4.12.1
  # CCI doesn't allow us to use a relative path in the monorepo, so we have to refer to an
  # already-published orb in their registry.
  # Run `bazel run --stamp //rosetta/cci-orb:publish` to produce a new version.
  bazel: aspect-build/workflows@dev:5.4.3

workflows:
  bazel-setup:
    jobs:
      - bazel/setup:
          resource_class: aspect-build/aspect-cli
          context:
            - slack
