version: 2.1

parameters:
  perform_delivery:
    type: boolean
    default: false
  delivery_commit:
    type: string
    default: ''
    description: The commit to checkout and run the delivery from
  delivery_targets:
    type: string
    default: ''
    description: Ignore the target(s) that are listed in the delivery manifest
      and instead deliver these targets. Comma-separated list of labels.

# enable CircleCI's dynamic configuration feature
setup: true

orbs:
  slack: circleci/slack@4.12.1

jobs:
  # Vendored rosetta output for Aspect Workflows
  test:
    resource_class: aspect-build/aspect-cli
    machine: true
    working_directory: /mnt/ephemeral/circle/workdir/workflows
    environment:
      XDG_CACHE_HOME: /mnt/ephemeral/caches
      ROSETTA_CONFIGURATION: .aspect/workflows/config.yaml
    steps:
      - run:
          name: Configure Workflows
          command: configure_workflows_env
      - checkout
      - run:
          name: Check runner health (before run)
          command: agent_health_check
      - run:
          name: Branch Freshness
          command: rosetta run branch_freshness
      - run:
          name: Prepare archive directories
          command: rm -rf /tmp/aspect/artifacts /tmp/aspect/testlogs
      - run:
          name: Bazel test
          command: rosetta run test --workspace .
          no_output_timeout: 2.5m
      - store_artifacts:
          path: /tmp/aspect/artifacts
      - store_test_results:
          path: /tmp/aspect/testlogs
      - run:
          name: Finalization
          command: rosetta run finalization
            --workspace .
          when: always

  # Prepare archives that speed up boot time of fresh Bazel servers on cold instances
  aspect-workflows-warming:
    resource_class: aspect-build/aspect-cli_warming
    machine: true
    working_directory: /mnt/ephemeral/circle/workdir/workflows
    environment:
      XDG_CACHE_HOME: /mnt/ephemeral/caches
      ROSETTA_CONFIGURATION: .aspect/workflows/config.yaml
    steps:
      - run:
          name: Configure Workflows
          command: configure_workflows_env
      - checkout
      - run:
          name: Check runner health (before run)
          command: agent_health_check
      - run:
          name: Create warming archive
          command: rosetta run warming --workspace .
      - run:
          name: Archive warming tars
          command: warming_archive

workflows:
  version: 2

  default_workflows:
    jobs:
      - test:
          context:
            - slack

  bazel-warming:
    triggers:
      - schedule:
          # Every 4 hours on weekdays
          # M-F 8:05, 13:05, 16:05 PDT
          cron: '5 15,20,23 * * 1-5'
          filters:
            branches:
              only:
                - main
    jobs:
      - aspect-workflows-warming:
          filters:
            branches:
              only:
                - main
