steps:
  - label: ":aspect: Test"
    agents:
      queue: aspect-default
    command: |
      echo "--- :aspect-build: Workflows environment"
      /etc/aspect/workflows/bin/configure_workflows_env
      echo "--- :stethoscope: Agent health check"
      /etc/aspect/workflows/bin/agent_health_check
      echo "--- :bazel: bazel test //..."
      pwd
      rosetta bazelrc > /etc/bazel.bazelrc
      bazel \
        --nohome_rc \
        --output_user_root=/mnt/ephemeral/bazel/aspect-cli/__main__ \
        --output_base=/mnt/ephemeral/output/aspect-cli/__main__ \
        test \
        --config=workflows \
        --config=ci \
        --test_output=summary \
        --show_progress_rate_limit=1 \
        -- //...
      echo "--- :bazel: bazel build //:launcher //:cli"
      bazel \
        --nohome_rc \
        --output_user_root=/mnt/ephemeral/bazel/aspect-cli/__main__ \
        --output_base=/mnt/ephemeral/output/aspect-cli/__main__ \
        build \
        --config=workflows \
        --config=ci \
        --test_output=summary \
        --show_progress_rate_limit=1 \
        --remote_download_outputs="toplevel" \
        -- //:launcher //:cli
      # Use cquery to get the actual output paths (handles platform transitions on Linux)
      WORKSPACE_ROOT=$$(pwd)
      LAUNCHER=$$WORKSPACE_ROOT/$$(bazel --nohome_rc --output_user_root=/mnt/ephemeral/bazel/aspect-cli/__main__ --output_base=/mnt/ephemeral/output/aspect-cli/__main__ cquery --config=workflows --config=ci --output=files //crates/aspect-launcher)
      CLI=$$WORKSPACE_ROOT/$$(bazel --nohome_rc --output_user_root=/mnt/ephemeral/bazel/aspect-cli/__main__ --output_base=/mnt/ephemeral/output/aspect-cli/__main__ cquery --config=workflows --config=ci --output=files //crates/aspect-cli)
      echo "--- :aspect: aspect tests axl"
      $$LAUNCHER tests axl
      echo "--- :aspect: aspect demo template-demo"
      $$LAUNCHER demo template-demo
      echo "--- :aspect: aspect user user_task"
      $$LAUNCHER user user_task
      echo "--- :aspect: aspect user user_task_reexport"
      $$LAUNCHER user user_task_reexport
      echo "--- :aspect: aspect user user-task-manual"
      $$LAUNCHER user user-task-manual
      echo "--- :aspect: aspect user user-task-added-by-config"
      $$LAUNCHER user user-task-added-by-config
      echo "--- :aspect: aspect user user-task-subdir (in crates/aspect-cli)"
      (
        cd crates/aspect-cli
        $$LAUNCHER user user-task-subdir
      )
      echo "--- :aspect: aspect help"
      $$LAUNCHER help
      echo "--- :aspect: aspect-launcher --version"
      $$LAUNCHER --version
      echo "--- :aspect: aspect-cli --version"
      $$CLI --version
      echo "--- :aspect: aspect version"
      $$LAUNCHER version
  - label: ":broom: Format"
    agents:
      queue: aspect-default
    command: |
      echo "--- :aspect-build: Workflows environment"
      /etc/aspect/workflows/bin/configure_workflows_env
      echo "--- :stethoscope: Agent health check"
      /etc/aspect/workflows/bin/agent_health_check
      echo "--- :bazel: bazel run //tools/format:format.check"
      pwd
      rosetta bazelrc > /etc/bazel.bazelrc
      bazel \
        --nohome_rc \
        --output_user_root=/mnt/ephemeral/bazel/aspect-cli/__main__ \
        --output_base=/mnt/ephemeral/output/aspect-cli/__main__ \
        run \
        --config=workflows \
        --config=ci \
        --show_progress_rate_limit=1 \
        //tools/format:format.check
