#!/usr/bin/env bash
git diff --cached --diff-filter=AM --name-only -z | xargs --null --no-run-if-empty bazel run //tools/format --
if ! git diff --quiet; then
  echo "❌ Some files were modified by the pre-commit hook."
  echo "Please review and stage the changes before committing again."
  git diff --stat
  exit 1
fi
