"""Definition of linter tools

This is in its own package because it has so many loading-time symbols,
we don't want to trigger eager fetches of these for builds which aren't running linters.
"""

# gazelle:exclude linters.bzl
package(default_visibility = ["//:__subpackages__"])
