/*
 * Copyright 2022 Aspect Build Systems, Inc.
 *
 * Licensed under the aspect.build Commercial License (the "License");
 * you may not use this file except in compliance with the License.
 * Full License text is in the LICENSE file included in the root of this repository.
 */

// This file exists to make the go tooling happy. This package is generated by
// bazel in //third-party/github.com/bazelbuild/bazel/...
package proto
