# This is a Bazel workspace for the Gazelle test data.

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    npm_package_target_name = "{dirname}_pkg",
    pnpm_lock = "//:pnpm-lock.yaml",
)

workspace(name = "npm_package_target_referenced")
