#!/usr/bin/env bash
#
# Regenerate the list of Bazel flags that take a separate value, which the CLI
# uses to collect `-c opt` as one flag-plus-value pair instead of leaving `opt`
# behind as a target pattern. Run after a Bazel upgrade:
#
#   tools/gen_bazel_value_flags.sh
#
# The arity comes from `bazel help <command>`, which renders a flag that takes a
# value as `--flag (a string; default: "")` and a boolean as `--[no]flag`. Short
# forms appear as `--flag [-x]`, so a short form is emitted only when its long
# form takes a value — which is exactly `-c` and `-j`.
#
# Deliberately omitted: label-shaped flags from rule sets (`--//pkg:flag`) and
# their `--flag_alias` spellings. Bazel *requires* `=` for those, so accepting a
# space-separated value would make `aspect` take command lines that plain `bazel`
# rejects, and the repro commands we print would not run when pasted. A repo that
# needs more can extend the list from `config.axl`; see `bazel/flags.axl`.
set -o errexit -o nounset -o pipefail

SCRIPTPATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
OUT="${SCRIPTPATH}/../crates/aspect-cli/src/builtins/aspect/bazel/value_flags.axl"
COMMANDS=(build test run query cquery aquery coverage)

bazel_version="$(bazel --version | awk '{print $2}')"

# `  --flag (an int...)` / `  --flag [-x] (...)` take a value; `  --[no]flag`
# does not. Long form first, then the short form when the same line has one.
collect() {
    local command
    for command in "${COMMANDS[@]}"; do
        bazel help "$command" 2>/dev/null | sed -nE \
            -e 's/^  (--[a-z_]+) \(.*/\1/p' \
            -e 's/^  (--[a-z_]+) \[(-[a-zA-Z])\] \(.*/\1\n\2/p'
    done
}

mapfile -t flags < <(collect | sort -u)
if [ "${#flags[@]}" -lt 100 ]; then
    echo "error: only ${#flags[@]} value-taking flags parsed; is \`bazel help\` output shaped as expected?" >&2
    exit 1
fi

{
    cat <<EOF
"""The Bazel flags that take a separate value (\`-c opt\`, \`--jobs 8\`).

GENERATED by tools/gen_bazel_value_flags.sh from \`bazel help\` for Bazel
${bazel_version} — do not edit by hand. Regenerate after a Bazel upgrade.

Consumed by \`bazel/flags.axl\`, which hands it to the post-command
\`args.passthrough()\` bucket so a forwarded flag's value is collected with the
flag instead of being read as a target pattern. Version skew is benign in both
directions: a flag missing from this list simply still needs \`--flag=value\`,
and a stale entry only matters if someone types it.

A repo can replace the list for its own wrapper flags:

    load("@aspect//bazel.axl", bzl = "bazel")

    def config(ctx):
        ctx.tasks["build"].args.bazel_value_flags = bzl.flags.BAZEL_VALUE_FLAGS + ["--my_wrapper_flag"]

Label-shaped flags (\`--//pkg:flag\`) are absent on purpose: Bazel requires \`=\`
for those, so accepting a space-separated value would diverge from Bazel and
break the \`bazel …\` repro commands the CLI prints.
"""

BAZEL_VALUE_FLAGS = [
EOF
    printf '    "%s",\n' "${flags[@]}"
    echo "]"
} >"$OUT"

echo "wrote ${#flags[@]} flags to ${OUT#"${SCRIPTPATH}/../"}"
