// @generated by protoc-gen-es v1.8.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file cli/core/bazel/packages_metrics/package_load_metrics.proto (package metrics, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Duration, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto2 } from "@bufbuild/protobuf";

/**
 * @generated from message metrics.PackageLoadMetrics
 */
export declare class PackageLoadMetrics extends Message<PackageLoadMetrics> {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;

  /**
   * @generated from field: optional google.protobuf.Duration load_duration = 2;
   */
  loadDuration?: Duration;

  /**
   * @generated from field: optional uint64 num_targets = 3;
   */
  numTargets?: bigint;

  /**
   * @generated from field: optional uint64 computation_steps = 4;
   */
  computationSteps?: bigint;

  /**
   * @generated from field: optional uint64 num_transitive_loads = 5;
   */
  numTransitiveLoads?: bigint;

  /**
   * @generated from field: optional uint64 package_overhead = 6;
   */
  packageOverhead?: bigint;

  constructor(data?: PartialMessage<PackageLoadMetrics>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "metrics.PackageLoadMetrics";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PackageLoadMetrics;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PackageLoadMetrics;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PackageLoadMetrics;

  static equals(a: PackageLoadMetrics | PlainMessage<PackageLoadMetrics> | undefined, b: PackageLoadMetrics | PlainMessage<PackageLoadMetrics> | undefined): boolean;
}

