load("//bazel/rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "fswatch",
    srcs = glob(["src/**/*.rs"]),
    visibility = [
        "//crates/axl-runtime:__pkg__",
    ],
    deps = [
        "@crates//:notify",
        "@crates//:serde_json",
        "@crates//:thiserror",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "fswatch_test",
    size = "small",
    crate = ":fswatch",
    deps = [
        "@crates//:tempfile",
    ],
)
