//! Tests for the gRPC server surface exposed to `.axl`: construction and
//! lifecycle smoke tests plus end-to-end dispatch round-trips (unary,
//! server-streaming, client-streaming) through real tonic clients.

#[test]
fn grpc_axl_loads_and_constructs_server() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
type(srv)
"#
    )
    .unwrap();
    assert_eq!(result, "\"grpc.Server\"");
}

#[test]
fn grpc_code_constants_match_canonical() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
[grpc.Code.OK, grpc.Code.NOT_FOUND, grpc.Code.FAILED_PRECONDITION, grpc.Code.UNIMPLEMENTED]
"#
    )
    .unwrap();
    assert_eq!(result, "[0, 5, 9, 12]");
}

#[test]
fn grpc_status_constructible() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
s = grpc.Status(code = grpc.Code.NOT_FOUND, message = "missing")
type(s)
"#
    )
    .unwrap();
    assert_eq!(result, "\"grpc.Status\"");
}

#[test]
fn grpc_server_serve_binds_tcp_and_drains() {
    // Binds to :0 (kernel-assigned port), checks the resolved endpoint
    // includes a real port, drains cleanly.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
h = srv.serve()
ep = h.endpoint
h.drain_and_quit(timeout = 5000)
ep.startswith("tcp://127.0.0.1:")
"#
    )
    .unwrap();
    assert_eq!(result, "True");
}

#[test]
fn grpc_server_add_after_serve_raises() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
h = srv.serve()
h.drain_and_quit(timeout = 100)
srv.add(v2.CapabilitiesService(on_get_capabilities = lambda req, rpc: None))
"#
    );
    let err = result.expect_err("expected add-after-serve to raise");
    assert!(
        format!("{err}").contains("cannot add services after serve()"),
        "unexpected error: {err}"
    );
}

#[test]
fn grpc_server_serve_binds_unix_socket() {
    // Process-unique path so concurrent test binaries don't collide; the
    // stale-socket cleanup in bind_endpoint handles leftovers from prior
    // runs (it only removes the file when nothing is listening).
    let sock = format!("/tmp/axl-grpc-test-{}.sock", std::process::id());
    let script = format!(
        r#"
load("@bazel//grpc.axl", "grpc")
sock = "{sock}"
srv = grpc.Server(endpoint = "unix://" + sock)
h = srv.serve()
ep = h.endpoint
h.drain_and_quit(timeout = 5000)
ep == "unix://" + sock
"#
    );
    let result = crate::axl_eval!(script.as_str()).unwrap();
    let _ = std::fs::remove_file(&sock);
    assert_eq!(result, "True");
}

#[test]
fn grpc_capabilities_service_constructible() {
    // CapabilitiesService is generated by the service_server proc-macro
    // and exposed via the v2 proto shim.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
svc = v2.CapabilitiesService(on_get_capabilities = lambda req, rpc: None)
type(svc)
"#
    )
    .unwrap();
    assert_eq!(result, "\"grpc.Service\"");
}

#[test]
fn grpc_server_add_capabilities_service() {
    // Bind, attach a service, drain. Verifies the install() path through
    // tonic Routes works end-to-end with a real *Server<T>.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.CapabilitiesService(on_get_capabilities = lambda req, rpc: None))
h = srv.serve()
h.drain_and_quit(timeout = 500)
h.endpoint.startswith("tcp://127.0.0.1:")
"#
    )
    .unwrap();
    assert_eq!(result, "True");
}

#[test]
fn grpc_server_duplicate_service_raises() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.CapabilitiesService(on_get_capabilities = lambda req, rpc: None))
srv.add(v2.CapabilitiesService(on_get_capabilities = lambda req, rpc: None))
"#
    );
    assert!(
        result.is_err(),
        "expected duplicate add to raise: {:?}",
        result
    );
}

#[test]
fn grpc_v2_messages_accessible() {
    // Sanity check: messages from `v2_toplevels` reach .axl via the shim.
    let result = crate::axl_eval!(
        r#"
load("@bazel//proto/remote/execution/v2.axl", "v2")
d = v2.Digest(hash = "abc", size_bytes = 3)
d.hash
"#
    )
    .unwrap();
    assert_eq!(result, "\"abc\"");
}

#[test]
fn grpc_unary_dispatch_round_trip() {
    // End-to-end: handler defined in .axl, server bound on :0, client
    // connects to the resolved address, sends a unary request, gets back
    // the handler's response. Exercises every part of the macro's
    // dispatch path — proto deserialization, fresh-Evaluator handler
    // invocation, Starlark→proto unpack, tonic response.
    //
    // Using ActionCache.GetActionResult since the existing `service`
    // macro produces an ActionCacheClient (Capabilities has no client
    // wrapper today).
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

def on_get_action_result(req, rpc):
    # Echo back a size_bytes value derived from the request so we can
    # verify both directions of marshalling through the macro's dispatch.
    # `exit_code` is i32; we pack the request's `size_bytes` into it so
    # the round-trip is observable end-to-end.
    return v2.ActionResult(
        exit_code = req.action_digest.size_bytes,
    )

def on_update_action_result(req, rpc):
    return v2.ActionResult()

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ActionCacheService(
    on_get_action_result = on_get_action_result,
    on_update_action_result = on_update_action_result,
))
h = srv.serve()

# tonic's client endpoint parser expects http://; the server handle
# returns tcp://host:port. Rewrite for the client side.
addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ActionCacheClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
resp = client.GetActionResult(v2.GetActionResultRequest(
    action_digest = v2.Digest(hash = "deadbeef", size_bytes = 1337),
))

h.drain_and_quit(timeout = 5000)

resp.exit_code
"#
    )
    .unwrap();
    assert_eq!(result, "1337");
}

#[test]
fn grpc_capabilities_round_trip() {
    // The driving aspect-delivery use case: a stub server that
    // advertises exec_enabled = true so Bazel's capability check passes.
    // Verifies CapabilitiesService dispatch + the newly-added
    // CapabilitiesClient (which the existing example design needs).
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
load("@bazel//proto/semver.axl", "semver")

def _get_capabilities(req, rpc):
    return v2.ServerCapabilities(
        execution_capabilities = v2.ExecutionCapabilities(
            exec_enabled = True,
            # DigestFunction.Value enum: 1 = SHA256. Using the raw int
            # because the proto generates a nested-mod enum and the
            # nesting depth doesn't match a simple `Enum.MEMBER` access
            # path through the starbuf-derived constructor.
            digest_function = 1,
        ),
        low_api_version  = semver.SemVer(major = 2, minor = 0),
        high_api_version = semver.SemVer(major = 2, minor = 3),
    )

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.CapabilitiesService(on_get_capabilities = _get_capabilities))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.CapabilitiesClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
resp = client.GetCapabilities(v2.GetCapabilitiesRequest())

h.drain_and_quit(timeout = 5000)

[resp.execution_capabilities.exec_enabled,
 resp.execution_capabilities.digest_function,
 resp.low_api_version.major,
 resp.high_api_version.minor]
"#
    )
    .unwrap();
    // exec_enabled=True; digest_function read back as the enum's string
    // name ("sha256"); low.major=2; high.minor=3.
    assert_eq!(result, "[True, \"sha256\", 2, 3]");
}

#[test]
fn grpc_execute_round_trip() {
    // Execute is server-streaming with response type
    // `google.longrunning.Operation`. Verifies the longrunning shim is
    // reachable and that Operation flows through the macro's
    // server-streaming dispatch unchanged.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")
load("@bazel//proto/longrunning.axl", "longrunning")

def _execute(req, stream, rpc):
    # Two-message lifecycle: queued (done=False) then completed
    # (done=True). Both reference the request's action digest hash so
    # the test verifies request marshalling end-to-end too.
    op_name = "operations/" + req.action_digest.hash
    stream.push(longrunning.Operation(name = op_name, done = False))
    stream.push(longrunning.Operation(name = op_name, done = True))
    stream.complete()

def _wait_execution(req, stream, rpc):
    rpc.abort(grpc.Code.UNIMPLEMENTED, "no wait")
    return

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ExecutionService(
    on_execute = _execute,
    on_wait_execution = _wait_execution,
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ExecutionClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
stream = client.Execute(v2.ExecuteRequest(
    action_digest = v2.Digest(hash = "feedface", size_bytes = 8),
))

ops = []
for op in stream:
    ops.append((op.name, op.done))

h.drain_and_quit(timeout = 5000)
ops
"#
    )
    .unwrap();
    assert_eq!(
        result,
        "[(\"operations/feedface\", False), (\"operations/feedface\", True)]"
    );
}

#[test]
fn grpc_bytestream_service_constructible() {
    // Client-streaming dispatch surface: ByteStreamService takes a Write
    // handler whose signature is `(req_stream, rpc) -> resp`. This covers
    // construction + .add(); the end-to-end Write dispatch is covered by
    // `grpc_bytestream_write_round_trip` below via ByteStreamClient.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/bytestream.axl", "bytestream")

def on_read(req, stream, rpc):
    rpc.abort(grpc.Code.UNIMPLEMENTED, "no read")
    return

def on_write(req_stream, rpc):
    # Sum committed_size across the incoming chunks. Exercises the iter
    # impl of the macro-emitted __WriteReqStream wrapper.
    total = 0
    for req in req_stream:
        total += len(req.data) if req.data else 0
    return bytestream.WriteResponse(committed_size = total)

def on_query(req, rpc):
    return bytestream.QueryWriteStatusResponse()

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(bytestream.ByteStreamService(
    on_read = on_read,
    on_write = on_write,
    on_query_write_status = on_query,
))
h = srv.serve()
h.drain_and_quit(timeout = 500)
h.endpoint.startswith("tcp://127.0.0.1:")
"#
    )
    .unwrap();
    assert_eq!(result, "True");
}

#[test]
fn grpc_rpc_shim_accessible() {
    // google.rpc.Status is reachable through the rpc shim.
    let result = crate::axl_eval!(
        r#"
load("@bazel//proto/rpc.axl", "rpc")
s = rpc.Status(code = 5, message = "not found")
[s.code, s.message]
"#
    )
    .unwrap();
    assert_eq!(result, "[5, \"not found\"]");
}

#[test]
fn grpc_server_streaming_dispatch_round_trip() {
    // End-to-end server-streaming: handler pushes two responses
    // synchronously then calls stream.complete(); client iterates the
    // resulting stream and we verify both messages arrive in order.
    //
    // Using CAS.GetTree because GetTreeResponse is a v2 message (reachable
    // through the v2 shim) and `ContentAddressableStorageClient` is
    // produced by the existing client `service` macro.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

def on_find_missing(req, rpc):
    return v2.FindMissingBlobsResponse()

def on_batch_update(req, rpc):
    return v2.BatchUpdateBlobsResponse()

def on_batch_read(req, rpc):
    return v2.BatchReadBlobsResponse()

def on_get_tree(req, stream, rpc):
    # Two responses, distinguishable by next_page_token, then close.
    # Synchronous push then complete is the simplest pattern; the
    # framework also supports stashing `stream` for later pushes from
    # other code (long-running pattern).
    if stream.cancelled():
        return
    stream.push(v2.GetTreeResponse(next_page_token = "page-1"))
    stream.push(v2.GetTreeResponse(next_page_token = "page-2"))
    stream.complete()

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ContentAddressableStorageService(
    on_find_missing_blobs = on_find_missing,
    on_batch_update_blobs = on_batch_update,
    on_batch_read_blobs = on_batch_read,
    on_get_tree = on_get_tree,
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ContentAddressableStorageClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
stream = client.GetTree(v2.GetTreeRequest(
    root_digest = v2.Digest(hash = "abc", size_bytes = 3),
))

tokens = []
for resp in stream:
    tokens.append(resp.next_page_token)

h.drain_and_quit(timeout = 5000)

tokens
"#
    )
    .unwrap();
    assert_eq!(result, "[\"page-1\", \"page-2\"]");
}

#[test]
fn grpc_unary_abort_observed_by_client() {
    // rpc.abort on a unary RPC must surface to the client as a non-OK
    // status; the client wrapper raises, carrying the message.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

def on_get_action_result(req, rpc):
    rpc.abort(grpc.Code.NOT_FOUND, "no such action result")
    return

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ActionCacheService(
    on_get_action_result = on_get_action_result,
    on_update_action_result = lambda req, rpc: v2.ActionResult(),
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ActionCacheClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
client.GetActionResult(v2.GetActionResultRequest(
    action_digest = v2.Digest(hash = "missing", size_bytes = 1),
))
"#
    );
    let err = result.expect_err("expected aborted RPC to raise on the client");
    let msg = format!("{err}");
    assert!(
        msg.contains("no such action result"),
        "abort message not propagated: {msg}"
    );
}

#[test]
fn grpc_unary_wrong_return_type_is_internal_error() {
    // A handler returning a non-response value must produce an INTERNAL
    // status naming the offending type, not a hang or a panic.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ActionCacheService(
    on_get_action_result = lambda req, rpc: "not a proto",
    on_update_action_result = lambda req, rpc: v2.ActionResult(),
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ActionCacheClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
client.GetActionResult(v2.GetActionResultRequest(
    action_digest = v2.Digest(hash = "abc", size_bytes = 1),
))
"#
    );
    let err = result.expect_err("expected wrong-type return to raise on the client");
    let msg = format!("{err}");
    assert!(
        msg.contains("returned wrong type"),
        "wrong-type diagnostic not propagated: {msg}"
    );
}

#[test]
fn grpc_push_after_complete_stops_at_complete() {
    // complete() closes the channel; a later push raises inside the
    // handler. The client must still receive everything pushed before
    // complete() and a clean end-of-stream (close-with-success already
    // happened, so the handler's error has nowhere to go).
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

def on_get_tree(req, stream, rpc):
    stream.push(v2.GetTreeResponse(next_page_token = "page-1"))
    stream.complete()
    stream.push(v2.GetTreeResponse(next_page_token = "page-2"))

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ContentAddressableStorageService(
    on_find_missing_blobs = lambda req, rpc: v2.FindMissingBlobsResponse(),
    on_batch_update_blobs = lambda req, rpc: v2.BatchUpdateBlobsResponse(),
    on_batch_read_blobs = lambda req, rpc: v2.BatchReadBlobsResponse(),
    on_get_tree = on_get_tree,
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ContentAddressableStorageClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
stream = client.GetTree(v2.GetTreeRequest(
    root_digest = v2.Digest(hash = "abc", size_bytes = 3),
))

tokens = []
for resp in stream:
    tokens.append(resp.next_page_token)

h.drain_and_quit(timeout = 5000)
tokens
"#
    )
    .unwrap();
    assert_eq!(result, "[\"page-1\"]");
}

#[test]
fn grpc_request_metadata_reaches_handler() {
    // Headers set on the client surface in the handler via
    // rpc.metadata(). Echo the header back through exit_code.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/remote/execution/v2.axl", "v2")

def on_get_action_result(req, rpc):
    md = rpc.metadata()
    return v2.ActionResult(
        exit_code = 42 if md.get("x-test-token") == "sesame" else -1,
    )

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(v2.ActionCacheService(
    on_get_action_result = on_get_action_result,
    on_update_action_result = lambda req, rpc: v2.ActionResult(),
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = v2.ActionCacheClient(
    uri = addr,
    headers = {"x-test-token": "sesame"},
    timeout = 5000,
)
client.connect(None)
resp = client.GetActionResult(v2.GetActionResultRequest(
    action_digest = v2.Digest(hash = "abc", size_bytes = 1),
))

h.drain_and_quit(timeout = 5000)
resp.exit_code
"#
    )
    .unwrap();
    assert_eq!(result, "42");
}

#[test]
fn grpc_bytestream_write_round_trip() {
    // End-to-end client-streaming: the ByteStreamClient feeds a list of
    // WriteRequests as the request stream; the handler iterates them and
    // returns an aggregate. Exercises the macro-emitted __WriteReqStream
    // iter wrapper plus the client-side list→stream bridge.
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
load("@bazel//proto/bytestream.axl", "bytestream")

def on_read(req, stream, rpc):
    rpc.abort(grpc.Code.UNIMPLEMENTED, "no read")
    return

def on_write(req_stream, rpc):
    # Sum resource_name lengths across the incoming chunks (string field;
    # keeps the test independent of bytes-literal syntax).
    total = 0
    for req in req_stream:
        total += len(req.resource_name)
    return bytestream.WriteResponse(committed_size = total)

srv = grpc.Server(endpoint = "tcp://127.0.0.1:0")
srv.add(bytestream.ByteStreamService(
    on_read = on_read,
    on_write = on_write,
    on_query_write_status = lambda req, rpc: bytestream.QueryWriteStatusResponse(),
))
h = srv.serve()

addr = "http://" + h.endpoint[len("tcp://"):]
client = bytestream.ByteStreamClient(uri = addr, headers = {}, timeout = 5000)
client.connect(None)
resp = client.Write([
    bytestream.WriteRequest(resource_name = "abc"),
    bytestream.WriteRequest(resource_name = "de"),
])

h.drain_and_quit(timeout = 5000)
resp.committed_size
"#
    )
    .unwrap();
    assert_eq!(result, "5");
}

#[test]
fn grpc_status_fields_readable() {
    let result = crate::axl_eval!(
        r#"
load("@bazel//grpc.axl", "grpc")
s = grpc.Status(code = grpc.Code.NOT_FOUND, message = "missing")
[s.code, s.message]
"#
    )
    .unwrap();
    assert_eq!(result, "[5, \"missing\"]");
}
