name: Aspect Workflows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-build:
    runs-on: [self-hosted, aspect-workflows, aspect-default]
    steps:
      - uses: actions/checkout@v6
      - name: Pre-build CLI
        run: |
          echo "Build and upload CLI to remote cache"
          .aspect/bootstrap.sh

  build-task:
    runs-on: [self-hosted, aspect-workflows, aspect-default]
    needs: [pre-build]
    steps:
      - uses: actions/checkout@v6
      - name: Bootstrap
        run: .aspect/bootstrap.sh
      - name: Build Task (ASPECT_DEBUG=1)
        run: ASPECT_DEBUG=1 aspect build //...
      - name: Build Task
        run: aspect build --task-key build-gha //...

  test-task:
    runs-on: [self-hosted, aspect-workflows, aspect-default]
    needs: [pre-build]
    steps:
      - uses: actions/checkout@v6
      - name: Bootstrap
        run: .aspect/bootstrap.sh
      - name: Test Task (ASPECT_DEBUG=1)
        run: ASPECT_DEBUG=1 aspect test //...
      - name: Test Task
        run: aspect test --task-key test-gha //...

  lint-task:
    runs-on: [self-hosted, aspect-workflows, aspect-default]
    needs: [pre-build]
    steps:
      - uses: actions/checkout@v6
      - name: Bootstrap
        run: .aspect/bootstrap.sh
      - name: Lint Task (ASPECT_DEBUG=1)
        working-directory: examples/lint
        run: ASPECT_DEBUG=1 aspect lint //...
      - name: Lint Task
        working-directory: examples/lint
        run: aspect lint //...

  delivery-task:
    runs-on: [self-hosted, aspect-workflows, aspect-default]
    needs: [pre-build]
    steps:
      - uses: actions/checkout@v6
      - name: Bootstrap
        run: .aspect/bootstrap.sh
      - name: Delivery Task (ASPECT_DEBUG=1)
        run: ASPECT_DEBUG=1 aspect delivery --build-url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" --commit-sha $GITHUB_SHA //examples/deliverable
      - name: Delivery Task
        run: aspect delivery --task-key delivery-gha --build-url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" --commit-sha $GITHUB_SHA //examples/deliverable
